### ISSUE TITLE
Doraemon: Nobita's Resident Evil 2: gun does not hit enemies more than 1 tile away

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1019]
Using gun does not hit enemies more than 1 tile away. It works however when the enemy is in the next tile, but too hard to hit, as enemies attack you with ease, making the game too much difficult.

This issue was already known, but also now reported via email.

[Nobihaza 2 download](http://www42.atwiki.jp/nobitahazard-wiki/pages/228.html) (note it has a download password mentioned there). This game is Japanese only. Unpack with `unar` for proper file encoding when unpacking.

The first battle appears closer to the beginning, you can skip intro when asked. In the first map Nobita is in a cell and the first guy entering after a few seconds will drop a gun, which needs to be equipped from the standard game menu. Or just load [this savegame](https://github.com/EasyRPG/Player/files/442457/Save02.lsd.zip), which has the gun equipped, toggle it with the shift key. There are some enemies for testing in the room after the door on the left.

**Comment by Ghabry** [comment]
No idea which events do all the hit-checking. One part is extracted here https://github.com/EasyRPG/Player/files/443094/Project5.zip

Basicly it looks like a "raycast". The pistole gets the facing direction of the Player, then is moved in that direction and another event checks for an overlap with the zombie.

Because in master the facing reverts to bottom facing you can hit the zombie when you are above him and shoot (facing direction doesn't matter)

**Comment by Ghabry** [comment]
Exactly the same problem (ball shoots down) occurs in https://box.yahoo.co.jp/guest/viewer?sid=box-l-i5qy7tqslfppjd4q6yb2yvdxb4-1001&uniqid=75e31c72-f9c9-4843-be82-ad0f16542c75&viewtype=detail
Is maybe easier to debug there and you have a big optical hint :D

**Comment by Ghabry** [comment]
This got fixed by #1020
