### ISSUE TITLE
Battle Animation must be rendered above Pictures, not below

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1031]
Noticed by the Razas developer :+1: 

In the same step we should check that stuff above Pictures has enough buffer so it's always above even for huge Picture IDs... Maybe use 100.000 and enforce this as highest picture ID. We could just make all Z values much bigger then currently, I mean we have 31bit of storage :D

**Comment by fdelapena** [comment]
Note RPG Maker 2003 1.05 (and probably RPG Maker 2000 1.50) changed this behaviour :warning: (yeah, thanks Enterbrain).

The RPG Advocate [rm2k3 changelog](https://web.archive.org/web/20080325201422/http://www.phylomortis.com/html/rm2k3vh.html) says:

> The image priority of pictures and battle animations was reversed.

I guess (hopefully) there is some way to detect these engine differences, since the 2k value launch (and 2k3 compatibility adaptation to them).

**Comment by Ghabry** [comment]
I made my test with the offical 2k English version. Thanks for this note
