### ISSUE TITLE
Can't change button layout in portrait

### ISSUE THREAD

**Issue by OrdinaryMagician** [EasyRPG/Player#1041]
Whenever I try to change the buttons, the screen is forced to landscape. Any changes made there completely screw up the layout in portrait.

I don't even know what version I have installed because there's no "about" section or anything in the program, but it should be the latest available on the play store.

**Comment by Ghabry** [comment]
That's by design because we assumed nobody uses portrait ;)

@BlisterB. Work for you :D

**Comment by BlisterB** [comment]
Hi guys ! I've just obtain my diploma, major of the prom ! Hihihi

I think I'll do a better system next week, it should be possible to change
the layout during a game session.

Le 23 sept. 2016 8:10 PM, "Carsten Teibes" <notifications@github.com> a
écrit :

**Comment by OrdinaryMagician** [comment]
> That's by design because we assumed nobody uses portrait ;)

woooow, rude!

**Comment by Ghabry** [comment]
Hm, maybe Portrait is used by some because they want to use it like a gameboy. But depending on the device the game is not always displayed at the top but at the bottom...

**Comment by BlisterB** [comment]
@OrdinaryMagician do you really play with portrait mode ?

For the moment, the portrait mode is calculated from the landscape layout. To be able to change the portrait layout, we should force the user to configure separately two layouts. (Or asking a choice between automatic calculation and specific configuration).
We assumed that portrait mode is nearly not used, and because the default layout is good, we didn't add the possibility to change it.

Of course, we are ready to hear any suggestion. But based on our Google Playstore reviews, this features seems worthless (because it would complicate the UI a lot). Please, don't hesitate to answer my question, and describe the way you use our app :).

**Comment by fdelapena** [comment]
IMo it gets harder to place buttons with some precision, this gets specially tricky when you need to place multiple buttons in a row, they may easily collide or going a bit off screen.
Indeed allowing to setting up them in portrait would be nice (but still force landscape for this if the screen setting checkbox is marked).

**Comment by Ghabry** [comment]
Maybe don't use two layouts but use one layout and only store the button position for portrait and landscape individually.

Imo a blocker for portrait mode is @BlisterB that it depends on the device if the window is at the top or at the bottom of the screen. In case of top you can hold your smartphone like a gameboy :D

**Comment by OrdinaryMagician** [comment]
I really do play in portrait mode. It's more GB-like and it's not as easy to accidentally press certain buttons on the phone (which happens very often when I try to use anything in landscape).

**Comment by BlisterB** [comment]
Okay, I'll find a clean way to make coexist the actual system and the possibility to customize the portrait mode. I have a thing in mind which would be a good compromise :).
