### ISSUE TITLE
A bunch of Vampires Dawn bugs

### ISSUE THREAD

**Issue by OslikGaming** [EasyRPG/Player#1128]
#### Describe the issue in detail and how to reproduce it:
1) [x] Asgar "Life gift" doesn't scale from intelligence, just heals for 40. On RPG_RT it heals for ~50-60.
2) [x] Escape button always greyed out.
3) [x] Seems like equipment from "other" slot with status effect immunities not working. Like desert giants in desert still apply bleeding on heroes with item(protective bloodring on Asgar and Alaine) that gives bleed immunity. Same happened with ring giving silence immunity(protective ring).
- [x] Sunblock cloak that should block damage on world map in desert also not working(equipped on Valnar).
4) [x] Paralyze not working on enemies. Message "Enemy was paralyzed" is displayed but they keep to act normally. Can be reproduced by casting ice magic on enemies until "Enemy is paralyzed" appears.

https://drive.google.com/file/d/0B5F-baO8aHjrUTVXdFIxdWpBNDg - Game with savefile(currently in desert so everything can be reproduced easily) and log

**Comment by Ghabry** [comment]
Thanks for the detailed bug reports, we will contact you when we have any questions

**Comment by rohkea** [comment]
Some more Vampires Dawn bugs were reported in the IRC today, I’m copying them here lest they should get lost:

[] one important bug: if you fight and one of your Teammates get the sleep status(or anything else) it works after this battleround. looks funny if your mate is fighting while sleeping. it seems this bug is the same for enemys
[] if you encounter a random fight there is no animation into the battle - except fading
[] while walking in the worldmap I encounter some flickering in the clouds

**Comment by carstene1ns** [comment]
The flicker should have been fixed by #1062.

**Comment by Ghabry** [comment]
There is still color flicker when screen tone + rain happen. They will go away when the  "Affected by screen tone" handling for 1.12 Pictures is in as this breaks the assumption that there is a "screen" layer and everything below is tone changed.

In reality RPG_RT simply adjusts the palette of all objects that are affected by Tint... "slightly" faster than we can do ^^'

**Comment by Ghabry** [comment]
"Escape button always greyed out." and "if you encounter a random fight there is no animation into the battle - except fading" are fixed or have a patch.

**Comment by Ghabry** [comment]
"Sunblock cloak that should block damage on world map in desert also not working". Iirc this is implemented via terrain damage, therefore should be fixed #1393

**Comment by carstene1ns** [comment]
This one needs a final test.

**Comment by Albeleon** [comment]
#1394 The latest commit "Operations to UseSkill with source; GetHighestLeveledActor for menu special items" fixes the latest touches of the first checkbox. With this patch, all the issues here are fixed.

**Comment by Ghabry** [comment]
I partly reverted the fix for " Asgar "Life gift" doesn't scale from intelligence, just heals for 40. On RPG_RT it heals for ~50-60." in #1394, need to retest this.

**Comment by fmatthew5876** [comment]
> There is still color flicker when screen tone + rain happen. They will go away when the "Affected by screen tone" handling for 1.12 Pictures is in as this breaks the assumption that there is a "screen" layer and everything below is tone changed.
> 
> In reality RPG_RT simply adjusts the palette of all objects that are affected by Tint... "slightly" faster than we can do ^^'

Should be fixed by #1545

**Comment by Ghabry** [comment]
That was misleading, because the game is not RPG2k3 1.12.

The Tint issue was fixed months ago by removing the "screen tint feature" and using "individual sprite tint" only. (before we had a fast path which used screen tint when the tone was changing each frame but this caused rendering glitches).


But the last two remaining things:

- Asgar "Life gift" doesn't scale from intelligence, just heals for 40. On RPG_RT it heals for ~50-60.
Escape button always greyed out.

- Seems like equipment from...

are solved. Closing :+1:
