### ISSUE TITLE
Engine naming for RM2k v1.61

### ISSUE THREAD

**Issue by rohkea** [EasyRPG/Player#1138]
The English RM2k v1.61 is easy to detect, but how can it be named? 

Options for RM2k v1.61:

1. Rename older RM2k as 'Legacy' for older engines. Possible downside: Japanese RPG Maker 2000 v 1.50 is [still sold](https://tkool.jp/products/rpg2000/index), can we call it legacy if it’s still the only Japanese version available?
2. Name RM2k v1.61 as 'English', probably rename old RM2k as 'Japanese'. Possible downside: the English version v1.60 would be considered 'Japanese'.
3. Use something like 'EngineSecondMajorUpdate'. Possible downside: doesn’t seem intuitive.
4. Use something like 'EngineMessagePlaceholders'. Possible downside: doesn’t seem intuitive, not in line with other names.
5. Something else?

**Comment by carstene1ns** [comment]
Just listing the old names here:

option | engine
---|---
rpg2k | RPG Maker 2000 engine (v1.00 - v1.10)
rpg2kv150 | RPG Maker 2000 engine (v1.50 - v1.51)
? | RPG Maker 2000 (English  release) engine (v1.60 - v1.61)
rpg2k3 | RPG Maker 2003 engine (v1.00 - v1.04)
rpg2k3v105 | RPG Maker 2003 engine (v1.05 - v1.09a)
rpg2k3e | RPG Maker 2003 (English release) engine

**Comment by Ghabry** [comment]
I think we can ignore Rpg2k 1.60 and treat it like japanese because most people probably updated to 1.61 (only difference of 1.6 was "Pictures dont block interpreter"). I suggest waiting for a game that proofs my statement wrong before thinking about 1.6

The term "Legacy" is from the view of an European because the official  english release made the japanese & translated versions outdated.

I agree on using "Japanese" instead of "Legacy".
As suggested handling the English versions under one bit like "EngineEnglishRelease" would make sense. The english version is implicit also MajorUpdated. 1.61 would be ``EngineR
Pg2k | EngineMajorUpdated | EngineEnglishRelease`` (or simply return true in majorupdated function when the english bit is set becase is redundant?)
MajorUpdated swaps rendering order of Pictures and BattleAnimations, any better naming for this?

**Comment by carstene1ns** [comment]
What we need is some kind of list of "features" or quirks we need to distinguish by engine.
I think this way we could hide the "E" or "MajorUpdated" stuff and just keep `rpg2k` and `rpg2k3` as engines and only enable some flags related to the changes between the versions.

**Comment by rohkea** [comment]
> I think this way we could hide the "E"

Maybe it could make sense to add a second setting like --language for that? This could influence not only engine detection, but also things like Japanese suffixes in battle and symbols available in the Enter Hero Name box.

**Comment by CherryDT** [comment]
Actually I was asked about a possibility to make Japanese versions of the 2k 1.60+/2k3 1.10+ versions, but I had to tell them that it is next to impossible after all the changes we did (remember we originally had to port from Japanese to English...), at least in a reasonable budget. :) So I guess it won't ever happen, but if it does, it would mess up your naming yet again.

**Comment by Ghabry** [comment]
When this happens we can replace English with Cherry and Japanese with Legacy

**Comment by Ghabry** [comment]
Will this issue be solved by #1163 or are their any further open points?
