### ISSUE TITLE
RM2k battle: when a skill absorbs both HP and MP, a failure message is shown if only HP was absorbed

### ISSUE THREAD

**Issue by rohkea** [EasyRPG/Player#1153]
Steps to reproduce:

* Create a skill that absorbs both HP and MP, make it strong,
* Add it to a hero with a big level (to make sure the skill doesn't miss),
* Create enemy with few HP and zero MP,
* Test using the skill on the enemy.

RPG_RT result:

* 'HP absorbed' message is displayed, and then 'enemy defeated' message. After this, the enemy disappears.

Actual EasyRPG result:

* 'Skill failed' message is displayed ('Enemy was unaffected'). After this, the enemy disappears.

**Comment by carstene1ns** [comment]
Tested this with some slime group and do not get the "Skill failed" message, but instead some "MP decreased by 0", which should be hidden, too.

**Comment by Albeleon** [comment]
I bring some feedback.

Just like the instructions, I made a project with this enemy ( https://i.imgur.com/w0sknqP.png ) and this hero ability ( https://i.imgur.com/k4VQs2y.png ), and I recorded the battle both in RM2000 and EasyRPG.

RM2000 video (ignore the sound lag, that's a problem of mine): http://sendvid.com/b81od5dh

EasyRPG video (focusing only in the things relevant to this topic, not the rest): http://sendvid.com/xrsgb5lj
EasyRPG Console: https://i.imgur.com/drLtoQc.png

In the console there's nothing, but in the video itself, it says the enemy dodged the attack despite dying later (probably because of it, so it still affects it).

**Comment by Ghabry** [comment]
@Albeleon was this already fixed as part of your PR?

**Comment by Albeleon** [comment]
#1373 
Yes, it's solved.

**Comment by carstene1ns** [comment]
(this one should be fixed now)
