### ISSUE TITLE
RM2k battle: Change Enemy HP with Allow Knockout should trigger victory

### ISSUE THREAD

**Issue by rohkea** [EasyRPG/Player#1191]
The Change Enemy HP battle command can trigger victory in RPG Maker 2000, but not in EasyRPG.

Here is a test project (Degica’s RPG_RT, not Don’s, but Don’s should be same): 
[BattleBug.tar.gz](https://github.com/EasyRPG/Player/files/1034543/BattleBug.tar.gz)

As can be seen in this project, the EasyRPG ends up with a battle scene with no monsters in it. Trying to do a usual attack on a monsterless battle scene results in an infinite loop.

**Comment by Ghabry** [comment]
Not even downloaded but my educated guess is that your check is on the last event line and the actual bug is here: https://github.com/EasyRPG/Player/blob/master/src/game_interpreter_battle.cpp#L37
This check won't happen for the last executed event line.
(And that behaviour is wrong anyway as stated in https://github.com/EasyRPG/Player/issues/1180)

**Comment by rohkea** [comment]
No, this effect doesn’t depend on the line in which the event command is placed. I’ve just tested with adding more event commands, the battle still doesn’t end.

**Comment by Ghabry** [comment]
Is this problem exclusive to events that run at the beginning of the battle or does your real game use something different?
Because I can only reproduce it for the "beginning of battle" case.

**Comment by rohkea** [comment]
@Ghabry No, it’s not at the beginning of the battle, it’s when hero’s HP ≤30%. Here are the settings I use:
![The event I use](https://user-images.githubusercontent.com/3201243/27253501-8145ec5a-537e-11e7-8e5d-365f80b02802.png)

(I’ve tried it without ‘Abort Battle’, too. Didn’t work either way.)
