### ISSUE TITLE
Colored "Boxes" in Battle

### ISSUE THREAD

**Issue by Brianum** [EasyRPG/Player#1225]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows64

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

[Save05.zip](https://github.com/EasyRPG/Player/files/1157550/Save05.zip)

#### Describe the issue in detail and how to reproduce it:

![unbenannt](https://user-images.githubusercontent.com/2110869/28343879-dfa0151e-6c1f-11e7-9315-2f8e2c1ca3c8.png)

Colored boxes, if multiple "highlights" are on one battler at a time. These don't appear in RPG_RT.

Reproduction steps: In the Mesdor Sewers have the slime blobs poison you. The character starts to flash green periodically. The box visible in the screenshot appears once a second highlight (active battler, target of healing spell) becomes active. This also appears to happen with other status effects, for example a status effect like "bleeding" (Red flashing of the character) causes red "squares" to appear.

**Comment by fdelapena** [comment]
This one might be related with blitting optimizations (pixman related) in recent releases because I don't remember to get this issue months before. It seems to affect sprites with some operation such transparency, saturation or tone change in general when there is also a screen tone change.

It is easy to reproduce in the following test map, where affects to raindrop sprites, which have slight transparency by default:

https://easyrpg.org/play/?start-map-id=40&new-game

To reproduce, talk with the witch in the bottom left to enable rain, then "talk" with the second tree from the right to reproduce the issue. Depending on the color combination, the square is more or less visible. Screenshot:
![captura de pantalla de 2017-07-18 17-52-33](https://user-images.githubusercontent.com/174885/28344645-22d3afd2-6be2-11e7-829f-90d4974689cc.png)

Also seen recently in the game Desolate City in the final boss scene (does some lightning effect and shows a slightly square too). 

I guess this one may be tested with older releases (before 0.5.0). If the issue disappears then there might be some commit candidates to check.
