### ISSUE TITLE
Emscripten: Player crashes when a game folder name exists in the FS root

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1255]
Please fill in the following fields before submitting an issue:
#### Name of the game:
HOME

#### Player platform:
Emscripten port

#### Describe the issue in detail and how to reproduce it:
Emscripten FS creates a directory structure to make apps more compatible with the environment. Some standard directories are [created](https://github.com/kripken/emscripten/blob/incoming/src/library_fs.js#L1290) previously, including /home for a default `web_user` directory, but also /tmp, /dev, /proc, etc.

Even if the game does not exist, player [creates](https://github.com/EasyRPG/Player/blob/master/resources/emscripten/emscripten-post.js#L22) a lowercase game directory in the FS root, but will fail if the directory already exists, even before checking the game is available.

**Comment by Ghabry** [comment]
The simplest solution for this would be moving in a non-reserved subdirectory first and creating our directory structure there.
Disadvantage: Due to how the local storage save code works this will prevent all old savegames from being loaded because the directory base changed. No idea if you consider this a problem.

Custom save code like on rmarchiv.tk will be unaffected.
