### ISSUE TITLE
Ib fan translation uses the Japanese text entry field instead of the English one

### ISSUE THREAD

**Issue by rsclifford** [EasyRPG/Player#1272]
#### Name of the game:
Ib (Most recent English translation by vgperson)

#### Player platform:
Windows

#### Attach files (as a .zip archive or link them)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/1361426/easyrpg_log.txt)
[Save01.zip](https://github.com/EasyRPG/Player/files/1361432/Save01.zip)

#### Describe the issue in detail and how to reproduce it:
In the "Secret Room" of The Dungeon in Ib, there's a room where you have to enter a name in order to proceed. With the standard RTP, the name entry uses English characters, allowing you to enter it, but 
with EasyRPG, it uses the Japanese name entry instead.

To reproduce:
- Load the attached save
- Enter the northwestern room
- Answer "Sure" at the dialogue prompt, then speak with Garry (the man) three times
- Wait for the objects in the room to start shaking, examine the newly uncovered canvas in the northeast part of the room, then examine the northwesternmost bookshelf
- Choose "Read how to enter"
- Examine the back of the leftmost bookcase in the southeast part of the room
- Stand between the bookcase and Garry, face west, then examine the gap
- Examine the canvas, and choose "Close eyes, count to three"
- Pull the cord that appears
- Examine the rightmost orb and choose "Enter a word"

**Comment by carstene1ns** [comment]
Hello, thank you for the bug report.
I thought we would never break Ib, but now it happened... 🙁
Problem is here that we changed the name scene (which is used for hero naming generally) to appear in the language used for the guessed encoding of the game instead of being able to use any letters/glyphs by page switching.
In the case of Ib we guess Shift_JIS, which means Japanese input. This happens, because the Database terms we use for the detection are still Japanese in the translation (vgperson did not translate them, because they are not used in the game).
Only workaround for now is switching the game encoding to e.g. 1250 (either via RPG_RT.ini entry or command line) or "cheating" by using test-play mode (toggling switch 663).

**Comment by Ghabry** [comment]
Because the behaviour change in the input scene was in May this is a regression in 0.5.2.
