### ISSUE TITLE
VH1 blank screen after using the Portalble Portal given by the Witch

### ISSUE THREAD

**Issue by Mister-Dolus** [EasyRPG/Player#1308]
Please fill in the following fields before submitting an issue:
#### Name of the game:
Violated Heroine

#### Player platform:
Linux

#### Attach files (as a .zip archive or link them)
[save.zip](https://github.com/EasyRPG/Player/files/1451144/save.zip)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/1451137/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
One of the first missions you can take is delivering a package to an old Witch living in the NW woods near a graveyard. After you give her the package, she stops you before you leave and gives you a Portable Portal item. Once you use this item, you are taken to a map where you can choose where to travel. The problem is that once you select a location, all you get is a blank screen and the area never loads.

**Comment by KevinX8** [comment]
I can also confirm this happens on Android aswell, no matter where you use the portable portal it will always just go to a black screen once you choose a location, the error that appears on screen is "Actor ID 0 is invalid" and this shows up before even choosing a location.

**Comment by Ghabry** [comment]
Download of 170722: https://mega.nz/#F!0ChlQYJa!918hNc-SzjigT-yBqiaidw

**Comment by Ghabry** [comment]
That savegame generates tons of "Removing invalid state: 0" in my sanity check code. Due to how the state array is designed this looks like a bug on my side ^^'

**Comment by Ghabry** [comment]
The problem is the glitter effect (Events 53 & 54) which are parallel processes a run an endless loop using a Label (and Waits 👍) which sets a move route.

Selecting a teleport target invokes page 2 of E51 which does:
```
SetMoveRoute E53, <empty>
SetMoveRoute E54, <empty>
ProceedWithMovement <-- here it hangs
```
The ProceedWithMovement hangs endlessly because after the empty move routes are finished one frame later the PPs get there normal move routes again. But empty routes are handled special: They don't introduce a "wait for movement", they finish directly, so after calling these 2 commands the ProceedWithMovement will only wait until the intermediate movement (of the previous route) finishes and then continue.
