### ISSUE TITLE
Integrate EasyRPG Player into ScummVM

### ISSUE THREAD

**Issue by yegortimoshenko** [EasyRPG/Player#1310]
ScummVM now accepts RPG engines into their tree, see: [[1]](http://wiki.scummvm.org/index.php/Summer_of_Code/GSoC_Ideas_2017#Bring_your_own_Adventure_or_RPG), [[2]](https://youtu.be/QihSN7VCrB0?t=16m10s). IRC log:

```
<yegortimoshenko> now that scummvm accepts rpg engines, have you thought about
		 integrating into scummvm?  [18:55]
<fdelapena> hi, some months ago scummvm developers were checking easyrpg in
	    fact  [18:56]
<fdelapena> but plans were unclear yet IIRC
<yegortimoshenko> that'd be amazing  [18:57]
<Ghabry> Thats an interesting news, I checked if scummvm accepts rpg engines
	 when I joined the project around 6 years ago :D
<fdelapena> so it is confirmed, cool  [18:58]
<yegortimoshenko> however, EasyRPG Player is GPLv3+ while ScummVM is GPLv2+
<Ghabry> thats indeed a problem...  [18:59]
<Ghabry> Well, I see no problem in integrating EasyRPG into ScummVM... our
	 code is quite modular so would be still possible to provide both a
	 Scumm module and a standalone executable. As already done by the
	 (unofficial) libretro port.  [19:01]
<Ghabry> <fdelapena> hi, some months ago scummvm developers were checking
	 easyrpg in fact <-- Really? I must have missed this  [19:02]
<fdelapena> and they were in this channel
<fdelapena> yeah, probably missed that
<yegortimoshenko> most of easyrpg's required dependencies are already in
		 scummvm, except pixman  [19:03]
<Ghabry> I guess scummvm already has it's own library for Blitting. But using
	 pixman directly would be less amount of porting work obviously. (no
	 need to write another "ScummBitmap" class)  [19:05]
```

**Comment by Ghabry** [comment]
After some discussion in #scummvm yesterday this doesn't seem to be feasible currently due to multiple problems:

- "it’s not just like dumping the source code into the scummvm tree and changing a few API calls and it’s done."
- "the save game system is going to be totally different, the way it reads files from the filesystem is going to be totally different"
- "heavily uses the STL"
- Use of C++11
- License incompatible: GPLv2+ vs GPLv3+

Additionally scummvm does not allow dynamic loading of engines, they are a compile-time dependency and all engine sourcecode is directly put into the scummvm-git-repo. As you can see the attempt is totally different to e.g. libretro, which just have a small abstraction layer and otherwise don't really care about consistency.

Still keeping this open as I like the idea.

**Comment by Ghabry** [comment]
Closing this as I don't believe there will be ever any progress on this, at least not from anyone of the core dev team.
Additionally we already support libretro (though not upstreamed yet) which also gives you the advantages ScummVM has: A GUI, lots of options and high portability. I'm not a big fan of libretro but for our use case it is the superior solution.
