### ISSUE TITLE
VH1 secret diary missing texture

### ISSUE THREAD

**Issue by KevinX8** [EasyRPG/Player#1311]
Please fill in the following fields before submitting an issue:
#### Player platform: Android
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - [2017-12-03 22:25:35] Debug: libpng: iCCP: known incorrect sRGB profile
[2017-12-03 22:26:19] Debug: libpng: iCCP: known incorrect sRGB profile [2x]
[2017-12-03 22:26:19] Warning: libpng: IDAT: chunk data is too large
[2017-12-03 22:26:19] Warning: Invalid image: Picture/char_make\OP\ゲームスタートメッセージ
[2017-12-03 22:26:19] Warning: Image not found: Picture/char_make\OP\ゲームスタートメッセージ

**Comment by carstene1ns** [comment]
Hi, thanks for the bug report.

If you read the log file and error message again, you notice the library loading the png image (libpng) tells us it is broken. The message about it missing is because we try to load some fallback images (i.e. bmp) first.

Upstream bug: https://sourceforge.net/p/libpng/bugs/270/

It means we have to update from libpng 1.6.32 to 1.6.34 in https://github.com/EasyRPG/buildscripts/tree/master/android.

**Comment by Ghabry** [comment]
Interesting. Our 0.5.3 release has a regression again but this time it's not our fault 😱

**Comment by Valkyriekain** [comment]
Wait so did this ever get fixed?

**Comment by carstene1ns** [comment]
Yes, however, we have not pushed a new build to google play since then.

**Comment by Valkyriekain** [comment]
Oh wow that was a super fast response. Is easyrpg maker done? Like no longer being developed?

**Comment by Ghabry** [comment]
The Player is still under development you can subscribe to the beta channel on google play to get more updates.
Or you mean the editor with "Maker"? This is not done and not really developed.
