### ISSUE TITLE
Tileset wrong

### ISSUE THREAD

**Issue by Klauserus** [EasyRPG/Player#1313]
Game: Unterwegs in Düsterburg
Plattform:  Wii
Player Version: 699 Nightly

The graphics are wrong. So the arrangement of the individual Tileset areas is not correct. You can tell it by the tree. If you enter a map, they vote for half a second, then they are displayed incorrectly.

![c187be-1512585975](https://user-images.githubusercontent.com/1331889/33679072-f870de68-dabd-11e7-9bfe-746ece7d3326.jpg)
![fffe59-1512585915](https://user-images.githubusercontent.com/1331889/33679073-f896d7bc-dabd-11e7-96d4-62c9217b99d9.jpg)

**Comment by Ghabry** [comment]
thanks for the report. Is this reproducable at the beginning of the game? Otherwise please provide a savegame :)

**Comment by Ghabry** [comment]
Thats an oversight caused by the patch for #1198. The UiD tiles use "Right Frame" with "Fixed Animation".

https://github.com/EasyRPG/Player/blob/master/src/game_character.cpp#L203-L205

Before the rightmost check was "pattern != original_pattern", therefore this worked (and broke Razas :D).
To fix it the if needs another condition to check for fixed

```cpp
if ((walk_animation && (IsSpinning() || IsContinuous())) ||
    (animation_type != RPG::EventPage::AnimType_fixed_graphic && pattern != RPG::EventPage::Frame_middle))
```
