### ISSUE TITLE
Final Tear 3: Multiple minor bugs in the battle system

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1314]
#### Name of the game: Final Tear 3
https://rpgmaker.net/games/3983/

#### Attach files (as a .zip archive or link them)

[Final Tear 3.zip](https://github.com/EasyRPG/Player/files/1536844/Final.Tear.3.zip)

Is either Save12 or 13. The correct one is the one in the pyramide.

#### Describe the issue in detail and how to reproduce it:

Walk upstairs and talk to the chair.
A battle starts.

RPG_RT
![screenshot_20171206_221030](https://user-images.githubusercontent.com/1331889/33685600-6e620480-dad2-11e7-802a-5ba71376c11c.png)

EasyRPG
![a](https://user-images.githubusercontent.com/1331889/33685615-7d56bf26-dad2-11e7-99b9-5fcffa389556.png)

- [x] Wrong background used. Caused by an off-by-one error in the Terrain handing code. Correctly handled in Spriteset_Battle. Can be fixed by removing the else-case in SetupBattle(). **0.6**
- [x] Enemy is placed too far up
- [ ] #2575
- [x] The system bar above the FaseSets is missing
- [x] The bar is transparent

**Comment by Ghabry** [comment]
Maybe problem 1 and 2 are fixed already, needs testing.

**Comment by Ghabry** [comment]
1 is fixed by #1605 
2 is likely depending on bug 1 because this is a terrain option

**Comment by fmatthew5876** [comment]
It's possible with all the recent battle PRs some more of these got fixed

**Comment by Ghabry** [comment]
Except for the "small command window" (is one of the battle system types) everything looks correct now:

![Screenshot_20201013_231817-fs8](https://user-images.githubusercontent.com/1331889/95917380-7563ac80-0daa-11eb-9758-d0ad33c54452.png)

**Comment by rueter37** [comment]
Sadly I'm not able to find a clean way to code the small battle window feature. For anyone who feels up to taking on the task, here is the information I gathered about the small window feature:
- The small windows are only used in RPG Maker 2003 battles
- The liblcf parameter `window_size` in the `BattleCommands` chunk must be set to 1
- Every window in RPG Maker 2003 battles is displayed small except of the help window and message boxes
- Small windows have a height of 68 instead of 80 pixels
- The BorderY value of small windows is 4 instead of 8
- The content height of small windows is (window_height - 8) instead of (window_height - 16)
- Menu items in small windows have a height of 14 instead of 16 pixels
- The SP window in the traditional battle mode has a height of 24 instead of 32 pixels
- Menus in small windows show only 3 menu items despite the space being sufficient for 4 menu items (like in the normal sized windows)

**Comment by Ghabry** [comment]
moved remaining issue (small window) to new issue
