### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by Tom-III** [EasyRPG/Player#1317]
Would love to know if this is still active?

**Comment by Ghabry** [comment]
Yes, it's currently just progressing a bit slowly.

As you can see in the issues list many new tickets were opened (by me, based on email bug reports) less than a week ago and two PRs are ready for merging. Additionally the last commit was 1 month ago, which is not that far back.

Problem by now is that we solved most interpreter problems and solving the remaining ones becomes more and more difficult because these are mostly corner-cases...
See e.g. #1308. Finding the cause of this took ca. 3 hours and in the end it was solved with a three-line patch :/.

**Comment by Tom-III** [comment]
How about the Editor?

**Comment by Ghabry** [comment]
Neither really death nor alive

**Comment by KevinX8** [comment]
So he's schrodinger's cat?

**Comment by rohkea** [comment]
If you need an editor for EasyRPG, you could check out R48 by @20kdc (written in Java). The inteface is very different from the original editor, and is not as polished yet, but it supports the complete RPG Maker 2000/2003 format. If you’re adventurous enough, you can give it a try: https://github.com/20kdc/gabien-app-r48
