### ISSUE TITLE
Switch Player unable to load files with Japanese characters

### ISSUE THREAD

**Issue by KevinX8** [EasyRPG/Player#1363]
#### Name of the game:
VH1
#### Player platform:
Nintendo Switch

#### Describe the issue in detail and how to reproduce it:
The switch version is unable to load any images, only the UI text is displayed. Tested on homebrew launcher 2.0 on a 5.0.2 console
Log included: https://pastebin.com/1cBKAhzB

**Comment by carstene1ns** [comment]
I think you may have files with broken encoding instead. Not sure how you got the files transferred, but extraction may already corrupt the filenames.
Can you point us to the download link you used for the game and tell us what kind of filesystem your Switch uses? (Fat32, exFat) ?

**Comment by KevinX8** [comment]
The netty folder, https://mega.nz/#F!0ChlQYJa!918hNc-SzjigT-yBqiaidw, and my sd card is exFat, I inserted the sd card into my phone and loaded up EasyRPG android to make sure they weren't messed up, everything worked flawlessly there. So the files are definetly not at fault.

**Comment by carstene1ns** [comment]
Great, thanks! Will try to load it later. However, using Fat32 on 3.0.0 here. Not sure how "safe" using stuff on 5.0 currently is. At least we may rule out the possibility of a broken build then.

**Comment by KevinX8** [comment]
Any different for 3.0.0 then?

**Comment by carstene1ns** [comment]
Please try [this build](https://ci.easyrpg.org/job/player-switch/lastSuccessfulBuild/artifact/builds/switch/easyrpg-player.nro), we have updated our toolchain to use the latest libnx.

**Comment by Ghabry** [comment]
Could you try a card with Fat32 instead of exFat?
Can only be a libnx issue.

**Comment by Ghabry** [comment]
I still believe this is an encoding issue and Android is just smarter in handling it because the Linux driver is better then Nintendos ;).

Based on the log it looks like you launch VH1 directly (by putting the game files in the nro folder).

1. 
Could you move the game files in a subdirectory of the NRO and give the VH1 game folder a japanese name (just append one of the picture filenames to the folder name).
Then launch the nro, does the name shown in the game browser match the folder name or is it random garbage? (test on both Fat32 and exfat)

2. English games (games with just ASCII in filenames) work? THough because RPG_RT.ldb is parsed for VH I assume a yes.

**Comment by carstene1ns** [comment]
According to `#switchdev`, this is a general encoding problem with the switch's file system.
Data seems to be encoded in `Shift_JIS` while we want to have `UTF-8` nowadays.
Currently, we cannot avoid it for SD, however, games packed into the executable (romfs) or loaded from archive (soon™) will not have this problem.

**Comment by KevinX8** [comment]
Ok, hope that archive loading becomes a thing on the switch soon enough, thanks for the reply!

**Comment by juaniwck** [comment]
Has romfs loading been implemented on the switch yet? I'm trying to build an NRO with the precompiled elf but it can't find the game.

**Comment by carstene1ns** [comment]
No, it is not possible right now. I have a local branch where I did the necessary code changes, however last time I tried it did not work correctly. This might have been fixed in the meanwhile, though.
