### ISSUE TITLE
Suggestion: use combination of point resizing and bicubic scaling to improve image quality

### ISSUE THREAD

**Issue by msikma** [EasyRPG/Player#1366]
A short time ago I filed #1364 - but what I actually wanted to file was at the time was this.

At the moment, it seems that EasyRPG uses point resizing. A game window has to be sized a multiple of 320x240 in order to have consistent pixel sizes across the whole image. So when the viewport is slightly off, like in #1364, you get a combination of different pixel sizes in the rendered image:

![image](https://user-images.githubusercontent.com/1507745/40311832-4fa1b380-5d11-11e8-9377-14eae7d1733f.png)

That's why I would recommend the following: use point upscaling to render a buffer at the closest multiple of 320x240 to the viewport size. Then use bicubic scaling to get to the exact viewport size.

In my view, this is the best way to maintain the integrity of pixel art for arbitrary screen sizes.

Here's a comparison of the current behavior, plus an example in which I used point resizing and bicubic resizing:

* [point upscale only](https://i.imgur.com/y4qj0Rl.png)
* [point upscale plus bicubic](https://i.imgur.com/A8oRh7H.png)

I'm only checking this on Mac OS X, but I'm not sure on which other platforms this behavior is the same.

---

#### Name of the game:

Any.

#### Player platform:

Mac OS X 10.13.4, but I presume behavior is the same everywhere.

**Comment by Ghabry** [comment]
POC to implement this: https://github.com/EasyRPG/Player/compare/master...Ghabry:sdl-scaling

I removed ``SDL_RenderSetLogicalSize`` and did all the calculations manually, otherwise there is not enough control here :/. Makes the code quite long... Not sure if the calculations can be simplified. Also contains multiple equality checks to avoid recalculations/allocations.

There are now two textures:
``sdl_texture_game`` contains the unscaled 320x240 game surface and ``sdl_texture_scaled`` which contains the integer/nearest scaled game surface.

sdl_texture_game --(renders int scaled on)--> sdl_texture_scaled --(renders fractional scaled on)--> Display

When the window is a multiple of 320x240 in one dimension only int scaling is done.

**Comment by Ghabry** [comment]
Example: A window slightly larger than 640x480.

![Screenshot_20200814_162554-fs8](https://user-images.githubusercontent.com/1331889/90259787-e3dbcb00-de4a-11ea-83bc-124a6387cebf.png)
