### ISSUE TITLE
Not All Tracks Playing in Midi Files

### ISSUE THREAD

**Issue by Chriees** [EasyRPG/Player#1388]
---
#### Player platform:

Raspberry Pi 3 B+
Retropie
Easy RPG Player

#### Describe the issue in detail and how to reproduce it:

I just started one of my favorite RPG Maker games and found out that not all midi tracks are playing. I checked the midi file on my pc and it appears to be complete, just on the retropie easy rpg player it only play one or two tracks. Like in the opening scene the midi files consists of 20 tracks or so, i can only hear 2 playing at the same time.

**Comment by carstene1ns** [comment]
Hoi, thanks for your bug report!
In default configuration we use an internal midi sequencer (fmmidi) as fallback, which sounds "electronic".
Can you try installing a soundfont for timidity or using wildmidi (if available)?

**Comment by Chriees** [comment]
Thanks a lot for your fast rwspinse and excuse me for my late answer. Since i am a beginner concerning raspberry pi, i dont really know how to do what you asked for.
The music doesnt sound electronic, it just sounds as if some instrument tracks rlare missing. The rest sounds fine.
How do i install a soundfont or use wildmidi? Is there any further info that you need?

**Comment by carstene1ns** [comment]
@fmatthew5876 Yes, you need to configure wildmidi manually, because it does not ship a patchset on it's own. We [have some fallback logic](https://github.com/EasyRPG/Player/blob/master/src/decoder_wildmidi.cpp#L174-L218) to find timidity configuration when there is none available. However, wildmidi should support most of the features timidity has, but cannot use soundfonts.
You can see the used configuration file in the logfile. Can you provide the broken timidity configuration?

**Comment by fmatthew5876** [comment]
So I get this on the console in Player:
```
Debug: WildMidi: Using `/etc/timidity/timidity.cfg` as configuration file...
```

My timidity.cfg looks like this, it's the default one installed by Ubuntu 18.04 package.

```

# Instrument configuration file for timidity
# $Id: timidity.cfg,v 1.7 2005/09/03 19:26:03 hmh Exp $

# You can change just about every option in TiMidity++ using
# This config file.  Please refer to the timidity.cfg(5) manpage
# for more details

## If you have a slow CPU, uncomment these:
#opt EFresamp=d         #disable resampling
#opt EFvlpf=d           #disable VLPF
#opt EFreverb=d         #disable reverb
#opt EFchorus=d         #disable chorus
#opt EFdelay=d          #disable delay
#opt anti-alias=d       #disable sample anti-aliasing
#opt EWPVSETOZ          #disable all Midi Controls
#opt p32a               #default to 32 voices with auto reduction
#opt s32kHz             #default sample frequency to 32kHz
#opt fast-decay         #fast decay notes

## If you have a moderate CPU, try these:
#opt EFresamp=l
#opt EFreverb=g,42
#opt EFchorus=s
#opt s32kHz
#opt p64a

# Disabling some of the Midi Controls can help with the CPU usage a lot.
# The same goes to the VLPF, sample anti-aliasing and effects such as
# reverb and chorus

# By default, try to use the instrument patches from freepats:
source /etc/timidity/freepats.cfg

# alternatively, you can use the fluid-soundfont:
#source /etc/timidity/fluidr3_gm.cfg
#source /etc/timidity/fluidr3_gs.cfg
```

Switching from `freepats.cfg` to one of the other options it behaves like it did when timidity wasn't installed.

Having to configure stuff like this on Linux is sort of ok (You always ending up having to configure s*** on linux..). Having to do it on an android mobile device is pretty a show stopper. Someone downloads EasyRPG from the appstore, audio is broken. They just forget it and move, possibly leaving a bad review.

I'm trying to wrap my head about the midi situation.

What benefit do we get from wildmidi? Why not timidity or fluidsynth directly? I understand fluidsynth has an annoying glib dependency, but I would think quality and consistency in audio is more important than build system problems.

**Comment by fdelapena** [comment]
My two cents about some alternatives if FluidSynth is still not considered:

- There is a tool to convert .sf2 into Gravis UltraSound (.pat) spare samples + .cfg, but this might lose instrument information, however this is a way to get them supported by WildMIDI. Testing this scenario requires experimenting with SoundFonts and tools and may take some time/effort.
- The fluidlite approach as an alternative for a lightweight version without glib requires to parse .mid (SMF, standard MIDI file) by our own (we already have a SMF parser for the optional FMMIDI synth).

We should think on a synth which allows to control the loopstart when the 111 event is set. There are also some notes by Sormat about how MIDI initial silence gets skipped by RPG Maker / RPG_RT, apart on how to get midi ticks properly for an event command which depends on this. So, we need fine grained control on how to handle this behavior.

In case of using a system-provided FluidSynth as a dynamic library dependency, we really need to make sure we may control how MIDI is provided. If FluidSynth does not expose public API to control events (but I guess it allows this) then we could use it as-is, otherwise we could use the SMF parser from FMMIDI code and send these events to the synth. The second approach allows to use FluidLite in other ports for a more lightweight package, but still may require some effort.

Additionally, we could make sure about the license of some small SoundFont available out there are able to be distributed on GNU/Linux distributions without licensing issues. The mentioned SF2 could be discussed on most strict distribution mailing lists, mainly Debian (strict DFSG guidelines)  and Fedora (strict patent fear policies). There are also SF3, supported by FluidLite and very recent FluidSynth versions (vorbis compressed samples), but samples are still large and may require a lot of RAM on playback. Well, this point is not that critical, as GNU/Linux users are more used to the lack of 1:1 accurate compatibility and the large Fluid R3 is good enough for most distro needs ;).

**Comment by fmatthew5876** [comment]
So it turns out I didn't have the fluid gm and gs sound fonts actually installed.

So when it worked after commenting out `freepats.cfg` and selecting `fluidr3_gs.cfg` it's because it fell back to some default soundfont. I guess wildmidi has one built in right?

But now after installing `fluid-soundfont-gs` and `fluid-soundfont-gm` the midi audio stops working if I source one of their configs. I guess that's the lack of support for sf2 biting us. 

So far just by installing certain packages I go from barely working midi, to working midi, to not working at all. Call it user error, but the user experience of having to deal with all this is pretty crap.

The other side of this is that game developers will test their games against specific soundfonts. Now the player has a different soundfont and gets an entirely different experience.

It will ease portability if we can find one library or set of libraries that works on all platforms the same way.

There are problems with the windows midi playback too: #1418. The new solution should be able to play the windows `.dls` soundfonts.


> Additionally, we could make sure about the license of some small SoundFont available out there are able to be distributed on GNU/Linux distributions without licensing issues.

If we could find a decent soundfont with such permissive license that would be great. I image many of them could have problems though. Don't most of the popular ones have non-free package repos? Could EasyRPG player and the default EasyRPG soundfont could be separate packages on platforms where it's a problem?

The ideal would be to ship the windows soundfont for RPG_RT.exe compatibility, but I'm guessing the license probably doesn't allow that.

**Comment by carstene1ns** [comment]
Closing as "User configuration issue". :wink:
