### ISSUE TITLE
hh3 - Various sound and other issues.

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1418]
#### Name of the game:
Heaven and Hell Episode 3

#### Player platform:
Windows

All of these are observed in rm2k mode. I have no idea if rm2k3 is different. All of these were seen in the continuous binary.

- [x] - Calling "Open Menu Screen" command from an event plays the Select sound effect. This causes the sound to play twice from hh3's CMS.
- [x] - When you use a skill in the field that enables a switch, it's configured sound effect will not play.
- [x] - In battle when you select an action it plays the Select SE, but then when you select which enemy to target it does not play the Select SE as it does in RPG_RT.
- [x] - I have a spell which can only cure states that all end after battle. In RPG_RT, this spell is greyed out in the field menu. In EasyRPG, the spell is usable like any other healing spell.
- [x] - Characters with 2 handed weapons can also equip shields.
- [x] - When casting a healing spell from the menu, the MP amount doesn't render correctly. In this example, the cost should be 2. (see photo)
- [ ] - Mp3 music will stop playing when you take focus away from the game window. Midi music continues playing. The midi song will play to the end and then stop. It won't loop until you click back into the game window. This happens on Windows.

![bad_mp](https://user-images.githubusercontent.com/1198466/45789925-56889f80-bc50-11e8-984e-6573d3493292.png)

**Comment by Ghabry** [comment]
Hello, thanks for the report.

We have multiple fixes in the queue that are not in master yet.
Could you please retest with this binary: https://ci.easyrpg.org/view/Pull%20Requests/job/player-win32-pr/1697/
At least equipment and the bogus number rendering should be fixed.

and anything battle related with this binary:
https://ci.easyrpg.org/view/Pull%20Requests/job/player-win32-pr/1698/

> Mp3 music will stop playing when you take focus away from the game window. Midi music continues playing. The midi song will play to the end and then stop. It won't loop until you click back into the game window.

The problem here is that we use the MIDI feature provided by Windows, therefore we have basicly zero control over it.
This is no issue on other platforms because we use our own midi player there but under Windows we would get complaints because "it sounds different" :/.
I'm not 100% sure about this but when you download this repository: https://github.com/ghabry/timidity_gus and put it in C:\timidity our internal Midi player will be used.

**Comment by fmatthew5876** [comment]
> Could you please retest with this binary: https://ci.easyrpg.org/view/Pull%20Requests/job/player-win32-pr/1697/

This does fix the equipment and rendering bug.

> and anything battle related with this binary:
> https://ci.easyrpg.org/view/Pull%20Requests/job/player-win32-pr/1698/

This does fix the sound effect issue.

> > Mp3 music will stop playing when you take focus away from the game window. Midi music continues playing. The midi song will play to the end and then stop. It won't loop until you click back into the game window.

I wonder how RPG_RT.exe does it then?

I'd really like to get hh3 100% working in EasyRPG. It looks like we have a backlog of PR's to merge in. Please let me know if I can help with that.

**Comment by Ghabry** [comment]
The backlog will shrink a bit soon because we want to get 0.5.4 out.
I can ping you afterwards concerning battle stuff (if Albeleon doesn't reappear :/), 

> I wonder how RPG_RT.exe does it then?
I have no idea. The Midi of RPG_RT doesn't expose multiple MIDI Api issues, e.g. Since Windows XP when playing a new MIDI file there is a hang of a few seconds (just try any old game that has MIDI BGM, you will notice what I mean and it is very annoying).
Another problem is that MIDI volume changes affect since Vista the whole application volume, not just the MIDI volume, making volume operations on MIDI basicly useless. Also I'm not aware of a way to change the pitch.
Therefore most of what they are doing can't be through the normal MIDI API, no idea how that works.

**Comment by Ghabry** [comment]
I think RPG_RT uses DirectMusic for MIDI playback.
Not really an option for us because this is deprecated since years, and the DirectX SDK bundled with Visual Studio lacks the headers for it.

Would be enough if we would have a library that can decode DLS files :/

**Comment by fmatthew5876** [comment]
I guess there is no way to "play" the midi into a memory buffer? And then you can direct that into the normal player for wav?

Microsoft usually keeps deprecated things around forever to run old software.

One horrible idea would be to compile some simple direct music wrapper on an old windows vm into a static library. And then link that with the new build..

Do the open source midi solutions really sound different? I thought midi was just about getting the proper sound font. Or is that what you mean with the DLS file?

**Comment by Ghabry** [comment]
I would prefer to avoid hacky workaround :).
At least the Windows API doesn't support decoding to memory buffer afaik. We already support decoding into a PCM buffer via FmMidi and Wildmidi but they don't support loading soundfonts in DLS format (Windows Midi uses gm.dls in system32 directory). You will here the difference immediately.

To hear the different audio do what I wrote few days ago:

> I'm not 100% sure about this but when you download this repository: https://github.com/ghabry/timidity_gus and put it in C:\timidity our internal Midi player will be used.

**Comment by fmatthew5876** [comment]
Geez you're not kidding.

I just started with player on linux. What have you guys done to my poor midi's! They sound terrible.

Some way to standardize the sound across platforms would be highly desirable.

**Comment by fmatthew5876** [comment]
Here is one. It sounds fine in windows. Loud and jarring in Linux.

[audio.zip](https://github.com/EasyRPG/Player/files/2480877/audio.zip)

**Comment by fmatthew5876** [comment]
Another issue I noticed on Linux (not sure if other platforms).

On a map with midi music, in a battle when I kill the last enemy, the enemy fade out animation stutters. Actually the whole battle stutters. I think it's getting stuck trying to load some midi stuff.

This stuttering doesn't happen on maps with mp3 music.

I see this on the console:
```
fluidsynth: warning: Failed to pin the sample data to RAM; swapping is possible.     
fluidsynth: error: Unable to open file "/usr/share/sounds/sf2/TimGM6mb.sf2"          
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont "/usr/share/sounds/sf2/TimGM6mb.sf2"
fluidsynth: warning: Failed to pin the sample data to RAM; swapping is possible. 
```

Not sure why I'm seeing logs about fluidsynth if its using wildmidi.

**Comment by Ghabry** [comment]
@fmatthew5876 except for everybodies favourite music format the other 3 open issues should be fixed now, right?

**Comment by fmatthew5876** [comment]
Should be. I will retest master tonight to verify.

**Comment by fmatthew5876** [comment]
Other than the midi issues, everything here is fixed. There are many other issues describing the midi problems so I will close this.

**Comment by fmatthew5876** [comment]
The issue I had reported before about midi continuing to play on Windows when taking away focus no longer happens with master.
