### ISSUE TITLE
EasyRPG's "disembark vehicle" cmd doesn't operate the same as RM2K's

### ISSUE THREAD

**Issue by msikma** [EasyRPG/Player#1429]
Tested in the stable version and in a more recent dev build (2aa5292). Same version I used to test my last bug.

This affects a game I was playing but I've made a minimal test case that reproduces the problem.

---

#### Name of the game:
Vehicle test

#### Player platform:
OSX

#### Attach files (as a .zip archive or link them)
 - [Vehicle.zip](https://github.com/EasyRPG/Player/files/2450919/Vehicle.zip)
 - [easyrpg_log](https://gist.github.com/msikma/cb695910be988891e95a0ffbc6436a4e)

#### Describe the issue in detail and how to reproduce it:

The player is on a boat, sailing on the water. You hit an event and the following commands are executed:

- Move boat left, left, face up (the exact movement commands don't really matter, as long as you can walk a few tiles)
- Ride/Disembark vehicle

In RM2k, the "disembark vehicle" command is executed immediately, before the move command is over. After disembarking it's the hero character that performs the move command.

This appears to only occur when the event is placed by the shore so that disembarking is possible right at the start.

RM2k: disembark, then hero walks left two tiles and faces up.

![screen shot 2018-10-05 at 17 13 08](https://user-images.githubusercontent.com/1507745/46544600-5204ed80-c8c4-11e8-9095-b69e2a1383b6.png)

EasyRPG: does not disembark, boat goes left two tiles and faces up.

![screen shot 2018-10-05 at 17 21 38](https://user-images.githubusercontent.com/1507745/46544588-4b767600-c8c4-11e8-818f-1ec023c0e88b.png)

In the game I was playing this led to me being teleported to another map while still being a boat. 😄

**Comment by carstene1ns** [comment]
Hmm, seems like another corner case like the ones fixed by #1404.

**Comment by fmatthew5876** [comment]
It looks like the culprit is `Game_Player::GetOnOffVehicle()` which exits when `!IsMovable()`, which returns false when `IsMoveRouteOverridden()`

It looks `IsMoveRouteOverridden()` doesn't matter as it's 1 when the vehicle command is executed in RPG_RT but the actual move command hasn't started yet.

Probably `GetOnOffVehicle()` should be allowed if the player is not moving, regardless of whether move route is overriden or not.


### Here is the data supporting this:



I changed the event to this:
```
Move: Boat, Left, Left, Turn Up
Wait 0.0s
Get On/Off Vehicle
```

Both player and RPG_RT move the boat and do not disembark when the movement is done.

I changed the event to this:
```
Get On/Off Vehicle
Loop:
  OpenSaveMenu
```

Both player and RPG_RT disembark, and the save menu waits for the disembark to finish before popping up.

I changed the event to this:

```
OpenSaveMenu
Move: Boat, Left, Left, Turn Up
Get On/Off Vehicle
Loop:
    OpenSaveMenu
```

RPG_RT:

OpenSaveMenu commands don't trigger while player is disembarking

| Save | vehicle | move_commands.size() | move_route_index | remaining_step | move_frequency | move_route_override |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | 1 | 0 | 0 | 0 | 0 |
| 2 | 0 | 3 | 0 | 0 | 1 |
| 3 | 0 | 3 | 1 | 224 | 8 | 1 |
| 4 | 0 | 3 | 1 | 192 | 8 | 1 |
| 9 | 0 | 3 | 1 | 32 | 8 | 1 | 
| 10 | 0 | 3 | 1 | 0 | 8 | 1 |
| 11 | 0 | 3 | 2 | 224 | 8 | 1 |
| 17 | 0 | 3 | 2 | 32 | 8 | 1 |
| 18 | 0 | 3 | 2 | 0 | 8 | 1 |
| 19 | 0 | 3 | 3 | 0 | 8 | 0 |

Player:

| Save | vehicle | move_commands.size() | move_route_index | remaining_step | move_frequency | move_route_override |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | 1 | 0 | 0 | 0 | 2 | 0 |
| 2 | 1 | 3 | 0 | 0 | 8 | 1 |
| 3 | 1 | 3 | 1 | 224 | 8 | 1 |
| 4 | 1 | 3 | 1 | 192 | 8 | 1 |
| 9 | 1 | 3 | 1 | 32 | 8 | 1 |
| 10 | 1 | 3 | 1 | 0 | 8 | 1 |
| 11 | 1 | 3 | 2 | 224 | 8 | 1 |
| 17 | 1 | 3 | 2 | 32 | 8 | 1 |
| 18 | 1 | 3 | 2 | 0 | 8 | 1 |
| 19 | 1 | 3 | 3 | 0 | 8 | 1 |

**Comment by fmatthew5876** [comment]
Here are some more complex test cases:

```
Set Move Route, Freq 8, Player, Move Left, Turn Up, Move Left, Turn Up
Loop:
  Wait 0.0s
  GetOnOffVehicle
```

* RPG_RT: Boat moves left, left, turn up, player gets off


```
Set Move Route, Freq 7, Player, Move Left, Turn Up, Move Left, Turn Up
Loop:
  Wait 0.0s
  GetOnOffVehicle
```

* RPG_RT: Boat moves left, turn up, player gets off, player moves left, player turns up


```
Set Move Route, Freq 8, Player, Move Left, Turn Up, Wait, Move Left, Turn Up
Loop:
  Wait 0.0s
  GetOnOffVehicle
```

* RPG_RT: Boat moves left, turn up, player gets off, player waits, player moves left, player turns up

**Comment by fmatthew5876** [comment]
Here is one that causes a bug in `RPG_RT`. Better to let pictures explain this one:

Move the event down 1 square:

```
Set Move Route, Freq 8, Player, Move Up, Move Left
Loop:
  Wait 0.0s
  GetOnOffVehicle
```

Player moves up, starts disembark and faces left at the same time. Player faces left and is stuck in the water. The boat appears to move from the right.

![vehicle](https://user-images.githubusercontent.com/1198466/50731272-5690aa80-112e-11e9-81f9-6509bff75d73.gif)

**Comment by fmatthew5876** [comment]
More `RPG_RT` bugs! This time with airship

Parallel event with this:

```
While is in airship:
Set Move Route, Player, Right
Get On/Off Vehicle
EndIf
Wait 0.0s
```

Board the airship, airship lands immediately


```
While is in airship:
Set Move Route, Player, Right
Wait 0.0s
Get On/Off Vehicle
EndIf
Wait 0.0s
```

Board the airship, airship lands immediately

```
While is in airship:
Set Move Route, Player, Right
Wait 0.0s
Wait 0.0s
Get On/Off Vehicle
EndIf
Wait 0.0s
```

Board the airship, airship gets stuck in an infinite loop landing and boarding over and over again :exclamation: 

![vehicle2](https://user-images.githubusercontent.com/1198466/50732742-c6af2880-114e-11e9-841a-a9bbf703bc7b.gif)

**Comment by fmatthew5876** [comment]
I've made a simplified test to nail down the boat behavior

### Conclusions:

* GetOnOffVehicle always checks whether you can disembark onto the next tile (position, direction). If the next tile cannot be disembarked on, the command is ignored.
* GetOnOffVehicle doesn't care if you're in an active move route or not.
* When GetOnOffVehicle is used during an active move (`remaining_steps > 0`), whether the disembark can occur is checked against the next tile, but then the actual disembark happens on the same tile in the water. Both the player and vehicle finish the current walking animation, but since disembark forces the vehicle to face left, you see it animating from the right outside of the player. (RPG_RT bug)
* The interpreter will wait for GetOnOffVehicle movement to finish before continuing to the next event command.


### Analysis:

Setup a map with 5 vertically stacked tiles like this. All other tiles water.

| Tile | Event |
| --- | --- |
| Grass | |
| Water | |
| Water | Event (see below) |
| Water | Ship Start |
| Grass | Player Start |

Now create the player touch event

```
Move Route, Freq8, Ship, Move Up
WAIT
Get On/Off Vehicle
```

Get on the ship and step onto the event

| WAIT | Result |
| --- | --- |
| 0 | Ship moves |
| 1 | Ship partially moves for 1 frame, Player disembarks into the water |
| 7 | Ship partially moves for 7 frames, Player disembarks into the water |
| 8 | Ship moves, Player disembarks onto land |

Now change the move route to this

```
Move Route, Freq8, Ship, Move Right
```

| WAIT | Result |
| --- | --- |
| 0 | Ship moves |
| 1 | Ship moves |
| 7 | Ship moves |
| 8 | Ship moves |

Now change the event to this

```
Move Route, Freq8, Ship, Move Up
Wait 0.0s
Get On/Off Vehicle
Open Menu Screen
Open Save Menu
Battle Processing: Slime x2
```

Player disembarks into the water. Only when disembark animation is finished, then the menu appears, followed by save menu, followed by battle.


Now change the touch event to this:

```
Move Route, Freq8, Ship, Move Up
Wait 0.0s
Get On/Off Vehicle
```

Add this parallel map event:

```
If is in ship:
  Loop:
    If not is in ship:
      OpenSaveMenu
```

Now step onto the touch event. As soon as the disembark starts, the `OpenSaveMenu` loop will start.

**Comment by fmatthew5876** [comment]
All that was only for disembark, now we need to test embark

### Conclusions:

* Embarking the airship doesn't happen when `remaining_steps > 0`. You have to be completely on the tile.
* Embarking the ship has the same glitch as disembark when `remaining_steps > 0`. You can embark on the grass if you do it mid walk animation.
* Embark during a move with `move_frequency < 8` interrupts any remaining `stop_count` frames.

### Analysis:

Setup these horizontal tiles:

| Tile | Event |
| --- | --- |
| Grass | |
| Grass | Airship |
| Grass | Touch Event |
| Grass | Player |

Setup the event with this:
```
Move Route, Freq8, Player, Left, Left
WAIT
Get On/Off Vehicle
```

| Wait | Result |
| --- | --- |
| 0 | Player moves left, left |
| 1 | Player moves left, left |
| 7 | Player moves left, left |
| 8 | Player moves left, ascends, airship left |
| 9 | Player moves left, left |

Setup the event with this:
```
Move Route, Freq7, Player, Left, Left
WAIT
Get On/Off Vehicle
```

| Wait | Result |
| --- | --- |
| 0 | Player moves left, left |
| 1 | Player moves left, left |
| 7 | Player moves left, left |
| 8 | Player moves left, ascends, airship left |
| 9 | Player moves left, waits 1 frame, ascends, airship left |
| 12 | Player moves left, waits 4 frames, ascends, airship left |
| 13 | Player moves left, left |


Setup these horizontal tiles:

| Tile | Event |
| --- | --- |
| Water | |
| Water | Ship |
| Grass | |
| Grass | Touch Event |
| Grass | Player |

Setup the event with this:
```
Move Route, Freq8, Player, Left
WAIT
Get On/Off Vehicle
```

| Wait | Result |
| --- | --- |
| 0 | Player moves left, stuck |
| 1 | Player moves left 1 frame, embarks the ship on the grass (see gif) |
| 7 | Player moves left 7 frames, embarks the ship on the grass |
| 8 | Player moves left, embarks |
| 9 | Player moves left, embarks |

![vehicle6](https://user-images.githubusercontent.com/1198466/50740228-29d5a500-11b9-11e9-89d4-8c9b50dea5f6.gif)


Setup the event with this:
```
Move Route, Freq8, Player, Left, Left
WAIT
Get On/Off Vehicle
```

| Wait | Result |
| --- | --- |
| 0 | Player moves left, stuck |
| 1 | Player moves left 1 frame, skips ahead to embark the ship in the water, ship finishes animation (see gif) |
| 7 | Player moves left 7 frames, skips to next tile to embark ship in water, ship finishes 1 frame animation |
| 8 | Player moves left, embarks, ship left |
| 9 | Player moves left, embarks, ship left |

![vehicle5](https://user-images.githubusercontent.com/1198466/50740176-b3d13e00-11b8-11e9-9815-63709c9c921c.gif)



Setup the event with this:
```
Move Route, Freq8, Player, ThroughON, Left, Left
WAIT
Get On/Off Vehicle
```

| Wait | Result |
| --- | --- |
| 0 | Player moves left, left |
| 1 | Same as non-through |
| 7 | Same as non-through |
| 8 | Same as non-through |
| 9 | Player moves left, left |

**Comment by fmatthew5876** [comment]
We're not done, what happens if we can embark multiple vehicles?

### Conclusions:

If multiple vehicles can be boarded, the order of precedence is:

1. Airship
2. Ship
3. Boat

### Analysis:

Setup these vertical

| Tile | Event |
| --- | --- |
| Water | Ship |
| Grass | Airship |
| Grass | Touch Event |
| Grass | Player |

Setup the event with this:
```
Set Vehicle Location of Boat to same tile as ship
Move Route, Freq8, Player, Up,
WAIT
Get On/Off Vehicle
```

| Wait | Result |
| --- | --- |
| 0 | Player moves up |
| 1 | Player moves up, boards ship on the grass |
| 7 | Player moves up, boards ship on the grass |
| 8 | Player moves up,  boards airship |
| 9 | Player moves left, left |

**Comment by fmatthew5876** [comment]
@CherryDT Lots of `RPG_RT` bugs for you

**Comment by msikma** [comment]
Thank you for the really excellent work to figure out exactly what's going on under the hood 👏 Really impressive!
