### ISSUE TITLE
Behavior of battle types in RM2k3

### ISSUE THREAD

**Issue by CherryDT** [EasyRPG/Player#1454]
I investigated how battle types behave in RM2k3.

[Click here to see my results](https://gist.github.com/CherryDT/8984e216dca3c0cd3c84f80b57006c16)

The answer is: somewhat erratically ;) So, part of this behavior would in my opinion also be a candidate for a compatibility mode as suggested [here](https://github.com/EasyRPG/Player/issues/1442#issuecomment-429996229)...

(Note that I didn't further dig into the calculations for battler placement, as these are probably less complicated to observe than the other things...)

The point of this issue is to discuss what Player _should_ do and how (and what it already does), and then track implementation.

**Comment by fmatthew5876** [comment]
How about the % chance of getting into particular kind of battle?

One of Albeleon's commits has this formula to determine whether an rm2k battle is first strike or not:

```
if (AvgPartyAgi > AvgEnemyAgi) {
    first_strike_rate = 5%
} else {
    first_strike_rate = 3%
}
```

Does that look right to you?

**Comment by CherryDT** [comment]
The chances to get into certain kinds of battles is set in the terrain setting in RM2k3.

For both RM2k and RM2k3, the chance of the "first strike" flag being set in a random encounter (which, as I realize now, may be set this way in RM2k3 also for battles other than "normal", even though this is not supported in the event command - not sure if this can have any weird effects then) is simply 1 out of 32, unrelated to AGI.

**Comment by Ghabry** [comment]
@fmatthew5876 

I think we implement everything now that Cherry lists except:

"
First of all, it's a bit weird because the battle type may not be what was set originally: Surprise is converted to initiative if the battler placement is "manual" or there is only 1 actor in the party. Pincers is converted to back if the battler placement is "manual" or there is only 1 enemy in the monster group. (Including the different effects on calculations explained below!)

It affects the placement of the battlers of course (position and mirroring).
"

**Comment by fmatthew5876** [comment]
We implement that too since the placement PR
