### ISSUE TITLE
Glitched map if the last tile of the chipset come as O

### ISSUE THREAD

**Issue by gadesx** [EasyRPG/Player#1577]
---
Please fill in the following fields before submitting an issue:
#### Name of the game: Test case of tomb raider game

Test case: https://easyrpg.org/play/master/?game=issue-1577

#### Player platform:
Windows 7

#### Describe the issue in detail and how to reproduce it:
There's a bug the only appear with player, it seems to ocurr
if the chipset it's not full, atleast the left part,
also from database, lower tiles, the last tile as O instead * seems to fix the glitched tileset.
I've added a copy of the chipset with more tiles that seem to work fine.
Works fine as O or * with rpg_rt.exe

**Comment by Ghabry** [comment]
Could you provide a test case for us?

**Comment by gadesx** [comment]
https://mega.nz/#!RjJ2QCrJ!XCMNC7cJqR20x2CrTkZP45eKf8iRx_7u6fx6xGcCaD0

**Comment by gadesx** [comment]
I selected and upped the testcase to github but nothing

**Comment by Ghabry** [comment]
This is an oversight in the "fast blit" codepath of the tilemap (which renders the bottom layer opaque to improve render performance). Not sure how to fix this yet.

**Comment by Ghabry** [comment]
I forgot about one corner case: There can be a lower layer tile a "star" tile which means it is drawn above upper layer tiles. In this case FastBlit must be disabled, otherwise the upper layer tile won't be visible BUT when the upper layer tile is transparent this will smear because the background is not drawn.

There is no simple way to fix this without tons of book keeping, so I will have to disable the minor speed optimisation (one memset of the screen to '0') and always clear the background.
