### ISSUE TITLE
Manually spin event is not working

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1654]
Create 2 events, one of them a charset with the graphic (the event to animate), the other one as parallel process with:

> @> Wait: 0.5 seconds
@> Set Move Route: [Event to animate], Turn Right
@> Wait: 0.3 seconds
@> Set Move Route: [Event to animate], Turn Down
@> Wait: 1.5 seconds
@> Set Move Route: [Event to animate], Turn Left
@> Wait: 0.3 seconds
@> Set Move Route: [Event to animate], Turn Up

In my case, the result is the charset graphic stay in the center position without animation.

**Comment by Ghabry** [comment]
could you please test this and the other stuff you reported against #1628 and #1601 

For 1628 you can use: https://ci.easyrpg.org/view/Pull%20Requests/job/player-win64-pr/1786/

For 1601: https://ci.easyrpg.org/view/Pull%20Requests/job/player-win64-pr/1773/

Test 1628 first, includes the code for 1601 (is just for determining whether the fix is in 1601 or 1628).

**Comment by Br4ssman** [comment]
It works, but with bad FPS 53-55 (probably because it's version to merge), but well, the manually spin event looks like good.

Thanks.

**Comment by Ghabry** [comment]
yepp the Windows debug builds are extremely slow, that's normal.
