### ISSUE TITLE
Performance: Improve interpreter setup

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1764]
via profiling I observed that in the very script heavy game "smashbros" 25% of all CPU time is consumed by ``list = _list`` (soon: ``frame->commands = _list``).

The only operations happening on this list are read and clear, therefore it is feasible to work on a reference instead of a copy but this change is not trivial.

by fmatthew:

> Since event code never changes, it should be possible to just use something akin to C++20 std::span to just point to the desired event buffer. That will require some surgery possibly at the liblcf level too.

**Comment by fmatthew5876** [comment]
One very stupid thing we do is reload completely when common events repeat themselves:

https://github.com/EasyRPG/Player/blob/master/src/game_commonevent.cpp#L50

So I think one quick win here could be to check if we're reloading the same event and if so, just "rewind" instead of copying the code again.

**Comment by Ghabry** [comment]
iirc the stacktrace of the Profiler was indeed from Common events, so this sounds like a feasible short-term solution.

**Comment by fmatthew5876** [comment]
Another thing:

https://github.com/EasyRPG/Player/blob/master/src/game_interpreter.cpp#L101

We'll probably need to change `IsRunning()` to `index >= list.size()`
