### ISSUE TITLE
gbstudio

### ISSUE THREAD

**Issue by arathron** [EasyRPG/Player#1824]
Just a crazy idea I had a minute ago: would it be posible for easyrpg to export the game to gbstudio, so that the game could be played on a real gameboy (or emulator)?

I know that easyrpg games have much more features that those available at gbstudio at the moment, but I mean if it would be posible for the subset of the features available in both.  Let's say for a new rm2k3 game suited to be played on both platforms (easyrpg player and gameboy)

https://www.gbstudio.dev/

**Comment by Ghabry** [comment]
Short answer: No. Lord Schoko made a joke game with EasyRPG logo though: https://twitter.com/Lord_Schoko/status/1119682528242274310

Long answer: Wellllll it depends. I don't think this will ever happen. The specs of the GameBoy are just too bad for this. If you want to target such a low-end platform you must design your application right from the beginning for it. Not even the database file of any RPG Maker game (~100 kbyte for small games) will fit into the 8 kbyte of GB memory :D.
Something that would be possible but is basicly an entire new engine project would be some kind  of "Export to GB Rom" function in the editor which exports the data in a special, compact format that is executed by an engine specifically targeting the GameBoy (that's how GBStudio does it I guess). 
With enough motivated this is feasible but otherwise I don't think it will ever happen, at least not as part of this project, sorry. Some kind of joke project for just exporting a map for GB sounds realistic but afterwards this slowly becomes too complex.

(This could be moved to Editor bug tracker but as I don't believe this will ever be resolved I'm in favor of closing it)

**Comment by arathron** [comment]
I was thinking an 'Export to gbstudio' that exportes the sprites (converts to 4 grayscale) and scripts into the json format of gbstudio.  That way the game would run both in easyrpg player, and in the gbstudio players (rom and web).
Of course it would be some kind of subproject of easyrpg, let's say 'easyrpgb', with resources tailored for this.

**Comment by ItsSchoko** [comment]
Making the map was super easy, I just had to throw some green tint on the existing RTP assets. (GBstudio does the rest.)
The actor on the other side was a problem, that might be something you would actually have to recreate.

If you want to check out how sad a resized Alex looks, the test game is also on GitHub:
https://github.com/ItsSchoko/EasyRPG-GB-Studio

**Comment by arathron** [comment]
What I mean is, it would be great to be able to create a gameboy game using easyrpg editor.

Of course, the game should be designed for gb from scratch: An 'easyrgpb' game, made with a subproject of the RTP-replacement (with 4-grayscale tiles).

And the resized Alex doesn't look too bad for me XD

**Comment by fdelapena** [comment]
> (This could be moved to Editor bug tracker but as I don't believe this will ever be resolved I'm in favor of closing it)

For a more Solomonic decision, and because this could (if even happens) be implemented as a tool before happening in Editor, I've added it to the tool suggestion issue, at https://github.com/EasyRPG/Tools/issues/15#issuecomment-507072088 to keep tracking this and closing it because it is unrelated to Player.
