### ISSUE TITLE
user files in linux

### ISSUE THREAD

**Issue by pirate486743186** [EasyRPG/Player#1928]
in accordance to XDG standard
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables

the log should go in .cache/easyrpg
the savefiles should go in .local/share/easyrpg

**Comment by Ghabry** [comment]
Related #666 
Don't think this is solvable without exposing a way to customize this via #1891.
At least "Keep in game folder" and "Store in [share/easyrpg]/Choose a path".

Besides from being incompatible to RPG_RT savefiles in a different directory has one unsolved problem: Preventing conflicts.

The saves must be put in subdirectories but how is the subdirectory supposed to be named?
 - Game name from INI is inconvenient because of encoding issues and many (mostly Japanese) games keep it at the default name.
 - Game folder name: Problematic e.g. for all popular translations by vgperson, they are all in a "Data" subdirectory
 - Database/MapTree hash: Works until you open the game in the editor and by looking at the folder names you have no idea to which game the savegames belong.

**Comment by pirate486743186** [comment]
easyrpg is already quite good.

**Comment by pirate486743186** [comment]
.

**Comment by pirate486743186** [comment]
.
