### ISSUE TITLE
"Wait for completion" option in scroll map is skipped

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1932]
**Name of the game**: SuperCrystal Hunter
**Player platform**: EasyRPG Player 0.6.1, Windows 10 x64
**Describe the issue in detail and how to reproduce it**:

In RPG_RT the camera focus waits to finish the scroll map, in Player you can move quickly and the camera go behind you until center the focus (once that you stop moving the event Player, of course).

https://fotos.subefotos.com/00e8e07ae5b197cecb909d7378d9e010o.png

**Comment by fmatthew5876** [comment]
I can't reproduce this with current master.

I setup this autostart event:
```
Scroll Right by 10, wait
Tint screen Green
EraseEvent
```

In both RPG_RT and Player, the screen scrolls, then it tints, and finally I am able to move the player.

**Comment by fmatthew5876** [comment]
I noticed something else in the test game provided by op in irc.

Start the test and press ESC. In RPG_RT, it'll load his custom cms pictures. In Player it'll load both that and the main menu.

**Comment by Br4ssman** [comment]
Yeah, no problem, since the starting point is there, the RPG Maker menu is not disabled.

**Comment by fmatthew5876** [comment]
> Yeah, no problem, since the starting point is there, the RPG Maker menu is not disabled.

Which is great, because this just exposed another bug. There is some condition in your code which when you summon the CMS something causes RPG_RT to not spawn the menu. But we aren't doing this in Player.

**Comment by fmatthew5876** [comment]
Test Cases 1 - Key input cancels active keys
=================

1.EV01 Parallel

```
KeyInputProc: Wait, key Cancel
ShowPicture
```

Result: Picture is shown and menu summoned

2. EV01 Parallel

```
KeyInputProc: Wait, key Cancel
ShowPicture1
KeyInputProc: Wait, key Cancel
ShowPicture2
```

Result: Picture1 is shown, menu is *not* summoned

3. EV01 Parallel
```
KeyInputProc: Wait, key Cancel
ShowPicture1
KeyInputProc: Wait, key Enter
ShowPicture2
```

Result: Picture1 is shown, menu is *not* summoned

4. EV01 Parallel
```
KeyInputProc: Wait, key Cancel
ShowPicture1
KeyInputProc: NoWait, key Cancel
If Var1 == 6:
  ShowPicture2
```

Result: Picture1 and 2 are shown, menu is *not* summoned

Conclusion
----------------

Executing a new key input proc command turns off all active keys.

This explains what is happening here:
https://github.com/EasyRPG/Player/blob/master/src/game_interpreter.cpp#L2699

We're actually disabling all the keys, instead of just waiting a frame.

**Comment by fmatthew5876** [comment]
Test Cases 2 - Key input proc and repeated keys
--------------------------

1. EV01 parallel
```
KeyInputProc: Var1, Wait, Directions, Enter
TintScreen Blue
KeyInputProc: Var2 Wait, Directions, Enter
```

EV02 parallel
```
Var2 = 0
KeyInputProc: Var2, NoWait, Directions Enter
If Var2 != 0:
  TintScreen Red
Else:
  TintScreen Normal
```

EV03 autostart triggered by Var1 >= 1
```
HideScreen: FadeOut
ShowScreen: Cut In
Var1 = 0
```

Press a direction or enter

Result: Screen is tinted red while we fade

2. Change EV02 to wait on the KeyInputProc

Press a direction or enter

Result: Screen is tinted blue while we fade

Conclusion
----------------

KeyInputProc Wait only resets triggered keys but not repeating!

**Comment by fmatthew5876** [comment]
Now back to the original issue here. It's with code like this:

```
ScrollUp (6, 4)
ScrollRight(1, 4, Wait)
```

RPG_RT will actually set the wait time to be `48` based on the larger and slower up movement, despite the wait being attached to the scroll right command.

In player, we only calculate the wait on the actual command it's attached to.

So we end up waiting 8 frames instead of 48 frames. That's the bug here.

**Comment by fmatthew5876** [comment]
Test Cases 3 Panning waits
-------------------------

EV01 parallel
```
Var1 += 1
```

EV01 trigger=action
```
Var1 = 0
SCROLL
Text: \v[1]
```

| SCROLL | Result |
| -- | -- |
| Up(2,4), Right(1, 4, Wait) | 16 |
| Up(2,4), Wait 0.1s, Var1=0, Right(1,4,Wait) | 10 |

Conclusion
---------------

Any wait attached to a pan command calculates the amount of time based on the remaining amount of pan from the screen chunks.
