### ISSUE TITLE
Skip jump in Event Player

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1936]
**Name of the game**: Super Crystal Hunter
**Player platform**: Player 0.6.1, Win10 x64
**Describe the issue in detail and how to reproduce it**:

Create an event as Player Touch, then introduce the next commands:
```
@> Set Move Route: Player,
$>Direction Fix ON
$>Through ON
$>Turn Left
$>Graphic: (center charset frame, in my case left graphic)
$>Wait
$>Wait
$>Jump
$>Turn right
$>Graphic: (another center charset frame)
$> Move Upper Right
$>Wait
$>Wait
$>Land
$>Turn left
$>Graphic: (another center charset frame)
$>Wait
$>Wait
$>Turn right
$>Graphic: (center charset frame, in my case left graphic)
$>Through OFF
$>Direction Fix OFF
@> Wait for All Movement
```
Basically it's a jump from the floor to a box and the change graphics are when the event Player prepare its jump (kneel, and change to normal frames)

**Comment by fmatthew5876** [comment]
Test Cases 1: Jump and directions

1. Make this touch event
```
OpenSaveMenu
MoveRoute: Player, Jump, Turn Right, Land
WaitForAllMovement
```

Step on the event from the right (so that you're facing left when you step on it)

| Save | direction | sprite_direction |
| -- | -- | -- |
| 1 | 3 | 3 |
| 1 | 2 | 3 |

2. Make this touch event
```
OpenSaveMenu
MoveRoute: Player, Direction FIX On, Jump, Turn Right, Land
WaitForAllMovement
```

Step on the event from the right (so that you're facing left when you step on it)

| Save | direction | sprite_direction |
| -- | -- | -- |
| 1 | 3 | 3 |
| 1 | 2 | 3 |
