### ISSUE TITLE
Picture affected by tint + weather commands doesn't work properly

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1945]
**Name of the game**: Super Crystal Hunter
**Player platform**: Player 0.6.1, Win10 x64
**Describe the issue in detail and how to reproduce it**:

I don't know if this issue was fixed o simply this function is not supported yet (being a new featured from rm 2k3 https://github.com/EasyRPG/Player/issues/1263).

In any case, I have this code:
```
@> Tint Screen: (100,90,120,100), @0.0s
@> Show Picture: 6, 'SCH-nevada', (0,-1), 100%, 15%, M6
@> Move Picture: 6, (320,240), 100%, 15%, @2.5s, Wait
```
"SCH-nevada" is my custom snowfall. But sometimes, there's an snowstorm and my snowfall is faster, besides, I add `@> Weather Effect Settings: Fog, Medium` for more realistic effect, and this is the result:

RPG_RT:
![Captura](https://user-images.githubusercontent.com/18174790/69128613-02c05300-0aad-11ea-8fcf-3e8519ebc52d.PNG)

Player:
![Captura2](https://user-images.githubusercontent.com/18174790/69128633-0bb12480-0aad-11ea-9757-eac6ceb03673.PNG)

**Comment by fmatthew5876** [comment]
Part (or maybe all??) Of this is due to the fact that we don't render fog and sandstorm effects accurately.

We just tint the screen whereas RPG_RT has a texture. It looks like for some levels of fog it even renders the texture over itself scrolling in different directions. So it's not easy to figure out exactly what is it and reproduce the effect.

Maybe someone knows how to hack RPG_RT and get the fog effect details out?

**Comment by Br4ssman** [comment]
Maybe @CherryDT can shed light on this issue.

**Comment by fmatthew5876** [comment]
Started on this here: https://github.com/EasyRPG/Player/pull/1992

It's never going to be perfect, but could use your help as you have a good eye for discrepancies.
