### ISSUE TITLE
Upgrade to Visual Studio 2019

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1965]
Some C++11 / 14 features don't fully work on VS 2017. We should upgrade our requirements to VS 2019 and change the build server to use it.

**Comment by fmatthew5876** [comment]
I've been able to succesfully build link and run player on vs 2019.

However I hit one snag.

I get linker errors from sdl2 about
```
unresolved external symbol __imp_SetupDiEnumDeviceInfo
```

Installing the windows sdk and adding `#pragma comment(lib "Setupapi.lib")` to one of our cpp files fixes this, but that seems like a hack? Maybe there is a better cmake way? Or maybe my system just isn't configured properly?

**Comment by Ghabry** [comment]
because this is a SDL2 dependency you can add it here:
https://github.com/EasyRPG/Player/blob/master/builds/cmake/Modules/FindSDL2.cmake#L241

There is no reason against installing VS2019, just lazyness to update:

![Screenshot_20191203_104129-fs8](https://user-images.githubusercontent.com/1331889/70039057-8acc4f80-15b9-11ea-9934-b38e96d01819.png)
