### ISSUE TITLE
TDF2018 Wild demo crashes in emscripten

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#2036]
https://easyrpg.org/play/master/?game=tdf2018wildcompodemo

Start a new game and the demo immediately crashes with an exception
```
uncaught exception: abort("Assertion failed: req != nullptr && req->IsReady(), at: src/cache.cpp,283,LoadBitmap")
```

**Comment by Ghabry** [comment]
That's not really useful.
Before replacing it with an assert there was a debug print "BUG: Not requested Path/Filename" providing a hint.

**Comment by Ghabry** [comment]
Using SAFE_HEAP + WASM debugging (really cool that this works now) this is a dangling reference to a Game_Picture when a "OnPictureReady" callback is fired. Dangling reference?

Can't test with WASM because the local server I use for testing (python http.server) does not support WASM streaming initialisation (whatever that is) and for array init the functions are too huge.

**Comment by fmatthew5876** [comment]
This could be the picture vector resizing itself in between file async operations.

**Comment by Ghabry** [comment]
Indeed: This must be caused by (Do)PreallocPicData. When I hardcode an array size there it doesn't crash.

**Comment by fmatthew5876** [comment]
I have an idea how to fix, and also add further picture performance improvements. Will look into after #2003 goes in.
