### ISSUE TITLE
Variables (names, attack points, gold) not being displayed on battles - TOWELKET 2

### ISSUE THREAD

**Issue by kurenaihana** [EasyRPG/Player#2040]
Name of the game: タオルケットをもう一度２：からあげたんぽぽ [_Towelket One More Time 2: Karaage Tanpopo_]

Player platform: Windows

Tested on latest continuous build.

I'm helping with the translation of Towelket 2 to English. The main translator notified me that the text in battle scenes still had some Japanese remaining that couldn't be translated. Upon closer inspection, I realized it was due to EasyRPG opening the game as the Japanese version of rm2k.

![3](https://user-images.githubusercontent.com/59675380/72035214-0040d500-3276-11ea-9d18-07b08a5ec162.png)

So I forced it to use the English RM2K through `--engine rpg2ke`, but then it didn't display any variable at all. That includes names, damage dealt to enemies, gold dropped, etc.

![0](https://user-images.githubusercontent.com/59675380/72035361-688fb680-3276-11ea-8c0c-b743baf405ea.png)

![1](https://user-images.githubusercontent.com/59675380/72035364-6af21080-3276-11ea-86f8-da6ef1219dc6.png)

![2](https://user-images.githubusercontent.com/59675380/72035369-6d546a80-3276-11ea-93c0-8d0c8e077c73.png)

The last line on the log says:
`[2020-01-09 00:11:14] Debug: Invalid read var[0]!`

Which seems to suggest the rm2ke version of EasyRPG is having problems with reading these variables.
Here's the full log attached:  [easyrpg_log.txt](https://github.com/EasyRPG/Player/files/4038447/easyrpg_log.txt)

Changing the encoding to 1252 fixes this problem, but also breaks all assets as they can't be read.

![4](https://user-images.githubusercontent.com/59675380/72035734-7d207e80-3277-11ea-9c50-caaf892f9ab5.png)

**Comment by Ghabry** [comment]
@kurenaihana 

These japanese characters (に) are injected when the encoding is Japanese (932). There is currently no way to disable this behaviour because encoding and game language are not a distinct attribute.

The reason why you don't get any output when using engine "rpg2ke" is that this engine supports placeholders.
2kE is the commercial release for the non-Japanese world. To get any output there you must use Placeholders in the message text field. The placeholders are:

- %S - Name of the attacker
- %O - Name of the attacked
- %V - The amount
- %U - The type of the value, e.g. "Atk" or "Def"

Btw when you save the game database once with the RPG Maker 2000 English edition Editor, Player will automatically detect this game as "2kE".

**Comment by Ghabry** [comment]
With minor tweaks this is solvable with our new translation feature:
Add a new entry ``LanguageCode=`` to the language Meta.ini and depending on whether the Code starts with "JA" enable/disable this.

**Comment by Ghabry** [comment]
this is implemented by now using ``Code=``. Only have to finish updating the website guide
