### ISSUE TITLE
Yume2kki pc_back Wallpaper Doesn't Load in 0.6.2

### ISSUE THREAD

**Issue by purupurupuruin** [EasyRPG/Player#2176]
#### Player platform:
Linux

#### Attach files
https://pastebin.com/5C1LQgXU (easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
In 0.6.1 using the pc_back customizable wallpaper in Yume2kki works:
![notborked](https://user-images.githubusercontent.com/64451846/80447547-8a1cb880-88ce-11ea-896e-7642e75c9b96.png)

But after updating to 0.6.2 the pc_back wallpaper doesn't load anymore.
![borkednow](https://user-images.githubusercontent.com/64451846/80447561-9274f380-88ce-11ea-8c16-cf24f8666f6d.png)

EDIT: Oh, forgot how to mention how to reproduce this:
Start a new game, skip the intro and head to the PC, select the Tools option, then Wallpaper, choose ON if you see a "New Wallpaper !!" notification with an ON/OFF option, and then choose the second option in the screen after that, and then the first option in the pc_back menu.

**Comment by Ghabry** [comment]
Never heard of this pc_back feature before. Reproduced it. thx.
At least this is not the default (otherwise we would have noticed it while fixing the music room), so won't affect many users.

**Comment by purupurupuruin** [comment]
Just in case this info helps fix the bug, the 2kki wiki states (https://yume2kki.fandom.com/wiki/Computer#Tools) that the game will accept any 256 color png/xyz/bmp image that's 320x240 pixels as pc_back

**Comment by Ghabry** [comment]
Thanks. I submitted patch.

This is one of the few games that uses "fancy" picture names like "..\Panorama\SomePic".

This causes two problems:
1. This is not a valid path on Linux (\-seperator)
2. We need to do case-insensitive file name mapping because Windows is case-insensitive

So that path must be somehow transformed to "panorama/somepic" and this was broken when the resulting path was in the game root dir ("..\pc_back -> pc_back")

**Comment by carstene1ns** [comment]
Once they figured out how to "hack" path traversal in the game, they absolutely must use this for such stuff.
They could have used `Picture` or `Panorama` subfolders as well, but they use the hack "for the lulz".
