### ISSUE TITLE
Yume2kki: Maiden Outlook background not showing properly

### ISSUE THREAD

**Issue by purupurupuruin** [EasyRPG/Player#2195]
#### Name of the game:
Yume2kki

#### Player platform:
Linux

#### Attach files (as a .zip archive or link them)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/4572958/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
The Maiden Outlook area in 2kki looks weird in EasyRPG:
![1](https://user-images.githubusercontent.com/64451846/80939992-39f09b00-8d93-11ea-93ff-ddc6e033d151.png)
![2](https://user-images.githubusercontent.com/64451846/80939997-3ceb8b80-8d93-11ea-9a5c-c7e1d3689641.png)

And here's how it's supposed to look:
![3](https://user-images.githubusercontent.com/64451846/80940002-3f4de580-8d93-11ea-8491-32838e62412d.png)

To reproduce:
Start/Load a game and head to the Maiden Outlook. (Sleep > Nexus > Library (Entrance looks like a roof) > read the book on the second bookcase to the left of the Library's entrance.
(Sorry if this ends up being a duplicate.)

**Comment by Ghabry** [comment]
Looks like a bug with panorama positioning. Thanks for reporting. Is not a known bug

**Comment by purupurupuruin** [comment]
I'll leave a debug save here to make this bug faster to find.
[maidenoutlook.zip](https://github.com/EasyRPG/Player/files/4589722/maidenoutlook.zip)

**Comment by purupurupuruin** [comment]
Just a small update to this bug, it's still present in 0.6.2.3 as well as the continuous build I downloaded a few hours ago.
Since I made that debug save in an older version of 2kki (0.112 I think), here's a debug save I made in 2kki ver 0.116 just in case:

[maidenoutlook2.zip](https://github.com/EasyRPG/Player/files/6419803/maidenoutlook2.zip)

By the way, for some reason, in 0.116 the menu no longer works in Maiden Outlook. (Not a bug, it's like that in RPG_RT too)

**Comment by Ghabry** [comment]
The expected pan_x is ``8960``.

When changing the panorama RPG_RT executes the following code:

```cpp
if ( !horScroll && !horLooping) {
    a = 16 * mapWidth - 20;
    b = max(0, imageWidth - 320);
    c = min(a, b);
    if ( b != 0 ) {
      pan_x = 2 * c * camera_pan_x / a;
    } else {
      pan_x = 0;
    }
  }
```

Player does:

```cpp
if (params.scroll_horz || LoopHorizontal()) {
	panorama.pan_x = map_info.position_x;
} else if (GetWidth() > 20 && parallax_width > SCREEN_TARGET_WIDTH) {
	panorama.pan_x = std::min(
		map_info.position_x * (parallax_width - SCREEN_TARGET_WIDTH) * 2 / ((GetWidth() - 20) * TILE_SIZE),
		map_info.position_x * 2);
	}
}
```

My guess is that this is also related to the async code: The image width is required but not available when determining it. Maybe make panorama change a blocking async op.

**Comment by Ghabry** [comment]
[Save04.zip](https://github.com/EasyRPG/Player/files/7836295/Save04.zip)

Some more bugs reported:
Load the Save and move to the left and then return to the previous map (This is necessary because pan chunks are not saved)

The door is misaligned:

![screenshot_5](https://user-images.githubusercontent.com/1331889/148707433-7f9f2a61-9fe7-4dd9-88c0-c5b68f61ad76.png)

Must be like this:

![screenshot_1](https://user-images.githubusercontent.com/1331889/148707425-63f4631f-1218-4083-9ffb-9b6d0282f48e.png)

Then go down the stairs, watch out for the jumpscare (See below)
In the next room the next issue:

![screenshot_6](https://user-images.githubusercontent.com/1331889/148707518-5b35908b-ee86-4d16-8340-7a33cbe4add6.png)

![screenshot_3](https://user-images.githubusercontent.com/1331889/148707507-6709049b-0574-4aed-a941-3124059d1382.png)

**Bug in the game**, not a Player bug:

When you go downstairs to the left there is a jump scare. Some quick flashing face.

![scare](https://user-images.githubusercontent.com/1331889/148707551-ba743c6d-2a7b-444b-bebf-311aef0bb4e2.png)

If you loaded the save, moved left, then right to the old room, left again and walk downstairs the face is misaligned:

![scare2](https://user-images.githubusercontent.com/1331889/148707541-bf16b3c7-a64c-4495-a819-d8e2e5edb314.png)

**Comment by Ghabry** [comment]
This is actually a difference between 2k and 2k3.

The face is misaligned only in 2k3, in 2k it is correct.

Here is a better savegame: Go through the door in front of you and then to the right until you see another door.
Then you are in the red room again.

[Save05.zip](https://github.com/EasyRPG/Player/files/7841161/Save05.zip)

With 2k:

![screenshot_8](https://user-images.githubusercontent.com/1331889/148821203-3096fc27-0839-460f-9aa5-5bfe4582d5b3.png)

With 2k3:

![screenshot_7](https://user-images.githubusercontent.com/1331889/148821199-d621ab10-5dbd-42bf-9b29-b0c22908c5dd.png)

**Comment by Ghabry** [comment]
There was a regression when loading async in the Yume2kki balcony and in MAP0947 (Wooden Polycube Ruins). These are also fixed.
