### ISSUE TITLE
Cannot hide numpad on 3DS build

### ISSUE THREAD

**Issue by bparisf** [EasyRPG/Player#2237]
#### Name of the game:
OFF

#### Player platform:
3DS

#### Describe the issue in detail and how to reproduce it:
Hello, all. I was hoping to find out whether the numpad could be hidden on the 3DS builds of EasyRPG. I'm using the latest build from the site, but can't seem to hide the numpad while in game. Any info you have on this would be greatly appreciated.

Cheers

**Comment by carstene1ns** [comment]
Currently, it is not possible. However, this has been requested before: https://github.com/EasyRPG/Player/pull/2086#issuecomment-610536356
There is a branch, I wanted to take a closer look: https://github.com/EasyRPG/Player/compare/master...Narwher:master

**Comment by bparisf** [comment]
I appreciate the info, will keep an eye on this development. Cheers

**Comment by Narwher** [comment]
I had an idea to use the 3D slider to toggle the touchscreen, since almost every other keybind is used by the interpreter. Not sure if that would work.

I need to update my fork, but my rough attempt allowed turning off the numpad overlay with 'Y' (the actual LCD is still powered on, however). There was some color-banding weirdness when the screen was turned back on however. I still need to get a grasp of the citro libraries before I do any more.

**Comment by bparisf** [comment]
Out of curiosity, was this request addressed in 0.6.2.3?
Cheers

**Comment by Ghabry** [comment]
I think this was fixed in #2617 ?

(pls reopen if wrong)
