### ISSUE TITLE
Battle2k3: Implement row for actors with no battle commands

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#2330]
Looks like there's an edge case we forgot, which is in the code:

https://github.com/EasyRPG/Player/blob/master/src/scene_battle_rpg2k3.cpp#L1472

Maybe this conditional just needs to be deleted now? 
Needs testing

**Comment by rueter37** [comment]
Removing that conditional works but not skipping actors which have the row command only introduces new problems: You can actually softlock yourself in traditional battle types if the other actors are in the back row (tested with RPG_RT and the removed conditional). In the alternative and gauge battle type you can break free from the softlock with the auto battle function because in auto battle the actor attacks even with attack command missing. By the way, we can change the comment in [https://github.com/EasyRPG/Player/blob/master/src/game_actor.cpp#L892](https://github.com/EasyRPG/Player/blob/master/src/game_actor.cpp#L892) from "not impl" to "row command is handled in scene_battle_rpg2k3.cpp".

**Comment by rueter37** [comment]
This is fixed by #2399. But it can lead to the [situation mentioned above](https://github.com/EasyRPG/Player/issues/2330#issuecomment-691433653).
