### ISSUE TITLE
[Feature Request] RPG Maker XP Game Support?

### ISSUE THREAD

**Issue by ThisNekoGuy** [EasyRPG/Player#2445]
#### Describe the issue in detail:
I wanted to request if someone can implement support for playing RPG Maker XP games?

**Comment by Br4ssman** [comment]
You should check out this project: https://github.com/Ancurio/mkxp

EasyRPG is just to maintain (and improve!) 2k/3 projects from now on and so, don't lose them along the time.

**Comment by Ghabry** [comment]
Sorry this is totally out of scope:

RPG Maker XP and VX (Ace) use completely different technologies, so we can't really support them without starting from zero.
Otherwise we would already support them :)

Please look at mkxp as linked above. They also have a Discord in case you have questions for them:  https://discord.gg/A8xHE8P
