### ISSUE TITLE
Libretro core built from here won't be able to load the saved core options.

### ISSUE THREAD

**Issue by Fishaphrodite** [EasyRPG/Player#2493]
#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game) : can be tested at the beginning of a game
 - The `easyrpg_log.txt` log file (you can find it in the game directory) : I don't think this file is generated using the libretro core

#### Describe the issue in detail and how to reproduce it:

When building the easyrpg-player as a libretro core, it seems the "core options" are being saved in the following way :

```
Debug Mode = "Enabled"
Input = "Use Both"
RetroPad L = "Open Debug Menu"
RetroPad L2 = "None"
RetroPad L3 = "None"
RetroPad R = "Walk through walls"
RetroPad R2 = "None"
RetroPad R3 = "None"
RetroPad X = "None"
```

Those options name have spaces in them, so they cannot be loaded properly (except "Input"), so they will always be reset to the default values when starting a game regardless of the core options file.

I actually talked about this issue first in https://github.com/batocera-linux/batocera.linux/issues/3475 , however I know batocera builds its libretro easyrpg core from this repository and not the libretro one (since the libretro one has a big message telling not to use it to build), so I opted to put it that information in here, I hope I'm not disturbing anyone with that.

**Comment by carstene1ns** [comment]
cc libretro/easyrpg-libretro#51

**Comment by Ghabry** [comment]
That they do not accept whitespace is undocumented but if this is the issue that is a quick fix. Will check.

Btw another open problem is that per-game overwrites and statistics do not work because retroarch looks at the filename (RPG_RT). this is nothing we can fix it seems.

**Comment by Ghabry** [comment]
> since the libretro one has a big message telling not to use it to build), so I opted to put it that information in here, I hope I'm not disturbing anyone with that.

Forgot to answer this. The libretro core is maintained upstream.

The sole purpose of the libretro fork is for offloading the libretro-core build on there buildbot. The repo is also "polluted" with a .gitlab-ci.yml and a copy of our buildscripts. Nothing we really want in the upstream repo.

That noisy ":warning: :warning: :warning: DON'T USE THIS FORK FOR YOUR OWN BUILDS / PACKAGES / ETC" is just because I was annoyed by reports for already fixed bugs (the fork is usually behind upstream) and by people who wanted to patch around in the buildscripts to cross-compile it for some Linux-ARM (which is bad practice anyway, they should use a buildroot and just invoke CMake...)
