### ISSUE TITLE
Wadanohara (vgperson) displaying error "can't set equipment" during the title screen

### ISSUE THREAD

**Issue by Fishaphrodite** [EasyRPG/Player#2506]
Please fill in the following fields before submitting an issue:
#### Player platform:
Linux (built from master 1 day ago I believe, maybe 2?)
#### Attach files (as a .zip archive or link them)
[Wadanohara_Set_equip_title_creen_issue.zip](https://github.com/EasyRPG/Player/files/6253106/Wadanohara_Set_equip_title_creen_issue.zip)

> Contains a screenshot of the issue, as well as the log (it seems to happen everytime the title sceen is accessed, and also when the game is closing, though that one won't be an issue).

> Log mentions a save, but it isn't required to reproduce (actually, the save was added afterwards just to try to go back from a currently running game back to the main menu).

#### Describe the issue in detail and how to reproduce it:
Open the translation by VGPerson of the game "Wadanohara and the great blue sea" (the Data folder is the game itself), and those error messages will pop up as the game tries to go to the title screen.

The issue isn't game breaking it seems so far, but it look wrong. (I didn't try to replay the game to see if those could be equiped or not during a regular playthrough).

**Comment by Ghabry** [comment]
This looks like a game bug.
Needs a check in RPG_RT maybe it simply ignores it than the warning can be changed from warning to debug.

**Comment by Ghabry** [comment]
This is caused by these lines here:

https://github.com/EasyRPG/Player/blob/c7b5a323bfb3f610fd1ab9cf01fecb22e365f016/src/game_actor.cpp#L89-L93

Wadanohara has invalid items in the actor equipment (out of range). ``SetEquipment`` shows a warning when the item is out of range. The Actor constructor needs a check and should debug log this.

**Comment by rueter37** [comment]
In RPG_RT the equipment slot is left empty (set to 0) if an out of range item is set in the initial equipment, so we have nothing game breaking here. We can change [line 300 in game_actor.cpp](https://github.com/EasyRPG/Player/blob/c7b5a323bfb3f610fd1ab9cf01fecb22e365f016/src/game_actor.cpp#L300) to `Output::Debug("SetEquipment: Can't equip item with invalid ID {}", new_item_id);` to make the message show only in the console.

**Comment by Ghabry** [comment]
What does RPG_RT do when you use set equipment event command with something invalid? They all use the same function

**Comment by rueter37** [comment]
RPG_RT crashes by doing so: A message dialog shows up which says: "Event script referenced an item that does not exist." In EasyRPG this case is caught by [lines 1656 to 1659 in game_interpreter.cpp](https://github.com/EasyRPG/Player/blob/c7b5a323bfb3f610fd1ab9cf01fecb22e365f016/src/game_interpreter.cpp#L1656-L1659).

**Comment by Ghabry** [comment]
hmm okay. Well instead of making the Warning "softer" I would prefer when we use in Game_Actor the same technique as we use for SetupBattleTest:
Assign all 5 equipment things to an array and then replace_if the stuff that is out-of-range with 0.
Everything that survives (in range but not equippable) is removed a bit later already :).

**Comment by rueter37** [comment]
Added a PR (#2511) now which should fix this issue.
