### ISSUE TITLE
Assets for Japanese Games tend to not work/dissapear

### ISSUE THREAD

**Issue by Rstation4** [EasyRPG/Player#2554]
Raspberry Pi 4 2gb
Lakka OS 3.1 aarch64 - Stable

I've tested 2 English Patched ".flow" games and English Patched "Yume 2kki" and I see that the assets are usually not found resulting in visual glitches and broken gameplay. 
Another thing is that when playing Yume Nikki has anyone notice some any issues with playing with a gamepad as a control? Sometimes when you try to leave the desk in the room you end up playing on the chair instead.

img: .flow (English Patched)
![RPG_RT-  flow](https://user-images.githubusercontent.com/73009731/121011895-fd3c6380-c74b-11eb-9603-d349abfeb165.png)

**Comment by Ghabry** [comment]
The problem here is that RPG_RT is not unicode aware so we must do language guessing.
Unfortunately this usually doesn't work for games that were translated from Japanese to English.

Instead you must do the following:

Edit the RPG_RT.ini and add:

```
[EasyRPG]
Encoding=932
```

Now the game should work.

There is no other way to configure this through the RetroArch core. This cannot be really added to the core options due to bad RetroArch behaviours: The options are shared across all games because they are all called RPG_RT.ldb, so the core options per game overwrite each other -_-

-------

Have to check the Gamepad problem
