### ISSUE TITLE
Logging support can not be disabled

### ISSUE THREAD

**Issue by gameblabla** [EasyRPG/Player#2565]
#### Attach files (as a .zip archive or link them)
![IMG_20210704_100648](https://user-images.githubusercontent.com/8717966/124378693-4e376d00-dca2-11eb-8d0b-4a079f5af0f4.jpg)

#### Describe the issue in detail and how to reproduce it:
There's no way in the codebase to disable logging support. This would require a bunch of ifdefs in output.cpp.
The reason why it is desirable to do so in the first place is because some games on some platforms may trigger the warnings.
The logging code itself also eats some RAM, which can be necessary on very low RAM SoCs like the JZ4725B.

**Comment by Ghabry** [comment]
The logging code uses almost no memory because it simply forwards to a file handle. except when a warning is displayed. Then it will eat up to half of the screen size in memory this is ~150 KB.

Except for dropping some dependencies I do not think you can slim down the player alot anymore.

With a proper hardware renderer which we still do not have one could use some kind of compressed texture format for the images. This could easily half the memory usage but I cannot think of any low hanging fruit

**Comment by gameblabla** [comment]
> The logging code uses almost no memory because it simply forwards to a file handle. except when a warning is displayed. Then it will eat up to half of the screen size in memory this is ~150 KB.
> 
> Except for dropping some dependencies I do not think you can slim down the player alot anymore.
> 
> With a proper hardware renderer which we still do not have one could use some kind of compressed texture format for the images. This could easily half the memory usage but I cannot think of any low hanging fruit

Yeah i was referring to mostly when it was displaying a message on screen. I almost commented out the asserts in the entire source code and it only marginally helped.
Dropping dependencies was effective (i only use fastwav and fmmidi) but for some reasons fluidlite won't work at all (probably a low memory issue) and only FMMidi would work and that thing is extremely slow.

> With a proper hardware renderer which we still do not have one could use some kind of compressed texture format for the images. This could easily half the memory usage but I cannot think of any low hanging fruit

I can tell you right away that this is out of question on low end hardware such as this one with no GPU acceleration available.

**Comment by Ghabry** [comment]
When we add the SDL resampler #2517 you could get proper resampling without libsamplerate/speexdsp and without a new dependency.

You can get rid of "libsndfile" when you pass "-DWANT_FASTWAV". But this only supports certain uncompressed WAV files, so extremely limited.

Yeah FmMidi has very high CPU usage unfortunately. Wildmidi is not an option because it needs ~16 MB RAM for the GUS files. FluidLite should work when you use a very small (< 1 MB) soundfont.

I can only recommend that you convert everything audio related to PCM WAV or MP3 beforehand, otherwise you are out of luck here.

Your device is really far too low-end.

Is it possible to add a swap-file to the device? Then you can maybe get a few more MB before it crashes :)

**Comment by gameblabla** [comment]
> Yeah FmMidi has very high CPU usage unfortunately. Wildmidi is not an option because it needs ~16 MB RAM for the GUS files. FluidLite should work when you use a very small (< 1 MB) soundfont.
I honestly would like to find where i could even find small soundfonts that could work with fluidlite... Would be nice as mine is several MBs.

> I can only recommend that you convert everything audio related to PCM WAV or MP3 beforehand, otherwise you are out of luck here.
That would work but it kinda defeats the point of having it work mostly out of the box.

> Is it possible to add a swap-file to the device? Then you can maybe get a few more MB before it crashes :)
There's an external sd card slot so it would be possible to add a swapfile in there but not every RG-99 might have one.

**Comment by Ghabry** [comment]
out of the box is not really an option for these devices.

Is also the main reason why we do not provide a port for the Play Station Portable:
The port works but almost no game works because the CPU is very slow and we run out of memory almost everywhere.

**Comment by carstene1ns** [comment]
The logfile part has been moved into #2838.
We already have enough memory related issues (3ds...), closing this one.
