### ISSUE TITLE
[Suggestion] Support for RPG Maker VX and VX Ace

### ISSUE THREAD

**Issue by Rstation4** [EasyRPG/Player#2615]
Also would it be possible to have support for Wolf RPG editors?

**Comment by Ghabry** [comment]
Sorry this is out of scope. Due to the ruby dependency and the tons of games that use DLLs this is a huge project.
You can take a look at mkxp https://github.com/Ancurio/mkxp and the fork mkxp-z https://gitlab.com/mkxp-z/mkxp-z

Wolf RPG is also a complete new engine and is still under active development. Though it says license is 'GPL" but no idea where the source code is 🤔 besides mad father I don't know a game using this one
