### ISSUE TITLE
Game Crashes randomly

### ISSUE THREAD

**Issue by LuisBristow** [EasyRPG/Player#2622]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform: 3DS
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)  I would attach a save, but the game crashes long before i can find a savepoint

#### Describe the issue in detail and how to reproduce it: 
When i get to the point in the game where you are first introduced to alinivar, you would go into a mr. Saturns house, talk to the mr. Saturn, leave to your cave and as the game enters a small cutscene, it crashes. Sometime i can make it through the cutscene and enter a battle with the painting. But during the painting battle, it will crash indefinately.

I tested cogdis on easy rpgplayer for windows and android, they work fine and smooth. I dont understand why its crashing on the 3ds so much. I was so happy to have a mobile version of this where my hands feel at home.

**Comment by fdelapena** [comment]
Hello, did you try the 3ds version from the "continuous builds" or the 0.6.2.3 version?

**Comment by LuisBristow** [comment]
I just downloaded the version on easyrpg player website

**Comment by LuisBristow** [comment]
Turns out the error isnt the rpgplayer its tge game. Apparently it has something to do with an image, it cant create 480 by 480 pixels image during a battle. Or something. I wish there was an easier way to resolve this.

**Comment by LuisBristow** [comment]
![Uploading 20210829_162531.jpg…]()

**Comment by fdelapena** [comment]
Unfortunately, when a "Can't create nnn x nnn image" usually means the 3DS runs out of memory. Because game authors didn't design their games thinking on low memory limitations (just games for a Windows PC), and 3DS having modest hardware capabilities. On the "New 3DS" or "New 2DS" the issue shouldn't happen because they have a lot more RAM available than the classic 3DS/2DS.

Please refer to the following (likely duplicate) issues:
https://github.com/EasyRPG/Player/issues/2184
https://github.com/EasyRPG/Player/issues/1135
https://github.com/EasyRPG/Player/issues/1097

**Comment by LuisBristow** [comment]
Hey i tried using a different build of easy rpgplayer. So thank you all forthe support and the help. It works, no crashing. Its a bit slow, but im not worried about speed. Im happy.

**Comment by fdelapena** [comment]
Thanks, which builds did you use before and after?
