### ISSUE TITLE
Windows: Native MIDI does not seem to reset properly between song changes

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#2732]
Windows, Native MIDI (wrong drum program after song changes):

https://user-images.githubusercontent.com/174885/155238764-20035824-24b5-4797-b895-eebfda0a6ab5.mp4

Windows, using soundfont, working as expected:

https://user-images.githubusercontent.com/174885/155238876-eb05ecac-3be8-4a18-9190-5905ef0fe51c.mp4

Game: [Ordo Quest](https://www.hellsoft.net/H5/component/remository/Juegos/Rpg-Maker-2000-Value/Juegos-Completos/Ordo-Quest/).

Thanks @MudarraP for reporting and video captures.

cc @tyrone-sudeium

**Comment by Ghabry** [comment]
Should be checked if ALSA Midi on Linux has the same problem

**Comment by tyrone-sudeium** [comment]
Harmony / RPG_RT must send some kind of reset signal to the device between tracks. I doubt it sends a full synthesizer reset command since that can cause some physical synthesizers to _literally reboot_, so it's probably some kind of controller reset on each channel.

I'll have to investigate with Sekaiju + LoopMIDI when I get some time

**Comment by Ghabry** [comment]
The difference is that RPG_RT also sends SysEx ``0xF0, 0x7E, 0x7F, 0x09, 0x01, 0xF7`` between songs (this is "Turn GM on")

Adding this fixes it for me.
