### ISSUE TITLE
Common resources for web hosting.

### ISSUE THREAD

**Issue by lychees** [EasyRPG/Player#2740]
Many rpgmaker games share some resources(e.g. RTP) and uploading them all separately seems to add a lot of unnecessary space and bandwidth cost, is there a way to set up a common directory to hold these default resources?

**Comment by Ghabry** [comment]
The web player has no RTP support because it was never really designed for running every game with it.

You must bundle all assets or use e.g. symlinks.

You can also use a server side solution here that manages the asset folder. (Mod_rewrite + PHP).

Then you have more flexibility about what to do when a RTP asset is requested.

Though not usable on itch.io & co.

**Comment by fdelapena** [comment]
Also consider converting all `Sound` and `Music` from wav (pcm/adpcm) and mp3 to Opus will do significant savings on most games at low bitrates (e.g. 32 or 24 kbps). It is possible to save around 10% (might vary) by recompressing images, mostly by converting them to xyz with png2xyz and applying xyzcrush from easyrpg tools. The RM 2000 RTP gets reduced from ~12 mb to at least ~4.7 using these tricks.
