### ISSUE TITLE
El Heredero del Rey (2003): Battle events not triggering properly

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#2753]
Please fill in the following fields before submitting an issue:
#### Player platform:
Tested on Emscripten in master but emscripten engine detection issues on battle are unlikely. Tested with engines rpg2k3, rpg2k3v105 and rpg2k3e without any difference.

#### Describe the issue in detail and how to reproduce it:
Start battle test 18. The enemy won't attack and defeating 99999 HP takes ages.
It shows there's some script (monster group event commands), as it shows a conversation, then it does not do anything else:
https://easyrpg.org/play/master/?game=ehr&battle-test=18

**Comment by Ghabry** [comment]
There are multiple problems here:

- Pages with Variables as conditions do not run at all except on battle start (surprising that this went unnoticed for so long). This one is a regression, matthew forgot this one in its huge refactor
- There must be some rounding behaviour for HP checks that we do not implement: In RPG_RT it continues already after 2 hits, in Player it takes ~30 hits until the 1-99% HP condition is fulfilled

**Comment by Ghabry** [comment]
The mail bug report about in Wolfenhain not being able to beat the Gate (Tor) in the Zyklopenberge via Wuchtattacke is the same problem with variables.

**Comment by Ghabry** [comment]
The HP check is indeed incorrect... Well, we are too correct ;).

We do "max_hp* hp_cond / 100" and then compare it to cur_hp so for the EHR battle this means the page triggers when the HP reaches "99999 * 99 / 100" = 98999. So the condition is true after receiving 1000 damage.

RPG_RT does "100 * cur_hp / max_hp" and then compares it against hp_cond. So this means even after receiving one single hit damage it is already true because "100 * 99998 / 99999" = 99.99 -> 99% after truncating the comma.
