### ISSUE TITLE
Maniacs Patch general tint bug/not implemented

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#2755]
Just put an pic with alpha channel, and modify its tint, via pic or tint screen.

This is an example of a pic imported normally:
![imagen1](https://user-images.githubusercontent.com/18174790/160155417-1f82ab58-ddcd-4950-b751-1bd40be0e629.png)

And I set its pic properties and:
![imagen2](https://user-images.githubusercontent.com/18174790/160155433-f27fef41-582e-4fed-93e1-86e85c807a1f.png)

Video showing how tint screen transform the normal picture to the bugged pone:
https://user-images.githubusercontent.com/18174790/160157150-41f5ddb8-0c38-4fd6-9db6-266868f364cb.mp4

Thanks.

**Comment by Ghabry** [comment]
The problem is that the alpha value was ignored (premultiplied alpha)

```cpp
static inline void color_tone(uint32_t &src_pixel, Tone tone, int rs, int gs, int bs, int as) {
	uint8_t a = (src_pixel >> as) & 0xFF;
	uint8_t r = ((uint32_t)hard_light.table[tone.red][(src_pixel >> rs) & 0xFF]) * a / 255;
	uint8_t g = ((uint32_t)hard_light.table[tone.green][(src_pixel >> gs) & 0xFF]) * a / 255;
	uint8_t b = ((uint32_t)hard_light.table[tone.blue][(src_pixel >> bs) & 0xFF]) * a / 255;
	src_pixel = ((uint32_t)r << rs) | ((uint32_t)g << gs) | ((uint32_t)b << bs) | ((uint32_t)a << as);
}
```

Unfortunately that multiply will make the blit even slower. Will do some benchmarking to figure out how bad it is and if special-casing ``a = 255`` will help.

![screenshot_1](https://user-images.githubusercontent.com/1331889/160711302-04586d9c-1b22-42c0-9f19-ceb7503e0aa6.png)

![screenshot_0](https://user-images.githubusercontent.com/1331889/160711085-13cf845e-70b7-413c-864e-8e03b95939a7.png)

**Comment by Ghabry** [comment]
@Br4ssman  please retest in master, this should look beautiful now :blush:
