### ISSUE TITLE
Feature: Common Event "ThisEvent" usage in RPG2000 games

### ISSUE THREAD

**Issue by florianessl** [EasyRPG/Player#2766]
I was pretty surprised there isn't already an option for this as this is one of the most valuable improvements in RPG2k3E and still missing from official RPG2kE versions: Using "This Event" in a Common Event to operate on the last map event in the call stack.

For me this is the most valuable improvement in the Steam version of RPG2k3 and makes all my code much more manageable. So it would be really great to be able to activate this feature for Rm2k games too.

**Comment by TrunXGIT** [comment]
Totally agree! A must have feature in my eyes. I'm currently making a game in rm2k with a more complex NPC interaction menu, I would be doomed if I was forced to use copy&paste and at a later point need to change a small detail of that interaction menu.^^

Fortunately there is a patch for the original rpg_rt.exe by Cherry that allows "ThiseEvent" in Common Events inside rm2k games.

Would be great if EasyRPG could either detect that Cherry Patch to unlock the feature or alternativly check an option inside the rpg_rt.ini. Something like "AllowCommonThisEvent=1".

Maybe it could even be unlocked by default? I can't imagine a case where it would cause a problem, since unpatched rm2k games could never used that event without a crash, and games that do thanks to some patch, would profit from it.

**Comment by Ghabry** [comment]
> I can't imagine a case where it would cause a problem, since unpatched rm2k games could never used that event without a crash, and games that do thanks to some patch, would profit from it.

Erase Event does not crash, instead it is a Noop. That is the only reason why it is disabled.

We know at least one Zelda game that breaks when "This Event" is enabled by default because it uses a noop-Erase Event in a common event that deletes then a crucial event. :D

**Comment by TrunXGIT** [comment]
Did the noop-Erase Event had a function under certain circumstances or was it a programming error with no consequences?
Anyway I see that it would be unfair to make that game that worked fine until now incompatible with future updates.
Would the optional ini-option be a suitable solution that a developer can set by hand to unlock the feature in a rm2k game?

**Comment by florianessl** [comment]
For information about the "CommonThisEvent"-Patch..:
https://www.makerpendium.de/index.php/CommonThisEventPatch
https://dev.makerpendium.de/docs/patch_db/main-en.htm?page=common_this_event

A port of this patch for the most recent Steam Rm2k release was also made rather recently.
Currently I'm hacking around a bit with features that are unique to Rm2k3 and adding them to projects made with the older engine. There doesn't seem to be a consistency in what the EasyRPG interpreter allows and what not..
For example: Using the extended ShowPicture/ErasePicture commands of the newer engine (which allows setting the PictureId via variables among many other new features) and just copy-pasting them to a Rm2k project will enable this functionality in EasyRPG without any need for custom compilation.
