### ISSUE TITLE
Questions about pre-processing resource files.

### ISSUE THREAD

**Issue by lychees** [EasyRPG/Player#2767]
Hi, as I mentioned last week, I am working on a pvp trading card game these days.

![image](https://user-images.githubusercontent.com/2507027/162626927-9909ccdc-955e-4c8f-b948-c7549f167fc8.png)

In the battle mode, I created a window to view the cards in deck and hand. However, on the web, these cards will not be loaded correctly. (But it will be correct if I summon those monsters directly before opening the menu!)

![image](https://user-images.githubusercontent.com/2507027/162626431-c99d0410-fa06-4e51-aced-9faefbe43367.png)

Here is what I do in the menu, how can I fix it?
```
		auto character_name = _.json[m.key]["charset"];
		int offset = _.json[m.key]["offset"];
		bitmap = Cache::Charset(character_name);
```

**Comment by Ghabry** [comment]
Due to how the web works the Player must fetch the files on demand. This works by creating a async request, returning to the browser and when the download is finished the event fires and the file becomes usable.

Search for ``AsyncHandler::RequestFile`` in the code.

To preload an image see e.g.: https://github.com/EasyRPG/Player/blob/c4b242f248c1aa932623d7e8b1f3c5c329737993/src/sprite_actor.cpp#L185-L188

- ``SetImportantFile(true)`` after returning to the browser the Player will "hang" until the download is finished
``SetGraphicFile(true)`` will mark the file as "Important" only when the screen is faded out. (makes map switches look better)

To preload on startup see (use with care): https://github.com/EasyRPG/Player/blob/87d422a063ac31d8b0af9a364e74f90dee09f227/src/scene_logo.cpp#L115-L144

The handle returned by ``->Bind`` must be saved somewhere. When this handle becomes invalid then the event will not fire.

-----------

On desktop these bound events will always fire immediately. This is bad when developing because you canot easily test the async behaviour.

To simulate the async behaviour outside of the web player comment out this define: https://github.com/EasyRPG/Player/blob/c4b242f248c1aa932623d7e8b1f3c5c329737993/src/async_handler.cpp#L41

**Comment by lychees** [comment]
It works~
Thanks again!
