### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by N4N4S2** [EasyRPG/Player#2798]
Estava jogando wadanohara and the great blue sea,e várias partes,dava como arquivo inválido,a texto estava péssimo e o menu estava verde,só me ocorreu com ele

**Comment by carstene1ns** [comment]
Sorry, but because of language barrier, we can only support in english on this bug tracker.

Your report is missing most valuable information. At least the platform you are using the player on must be known.

The issue is likely related to a wrong encoding, either on unpacking or detection.

---

Desculpe, mas devido à barreira linguística, só podemos apoiar em inglês neste localizador de insectos.

Faltam informações muito valiosas no seu relatório. Pelo menos a plataforma em que está a utilizar o leitor deve ser conhecida.

A questão está provavelmente relacionada com uma codificação errada, seja na desembalagem ou na detecção.

**Comment by carstene1ns** [comment]
Closing due to lack of information.
