### ISSUE TITLE
Arrow keys& Number keys Doesn't work properly.

### ISSUE THREAD

**Issue by Th10Lover** [EasyRPG/Player#2811]
Please fill in the following fields before submitting an issue:
#### Name of the game:

細胞神曲 -Cell of Empireo-

#### Player platform:

Windows(10, 21H1), PSVita(1000, 3.74 Final h-encore), Nintendo 3ds (old)

#### Attach files (as a .zip archive or link them)

Log Files
[PC-Continuous_build.zip](https://github.com/EasyRPG/Player/files/8928225/PC-Continuous_build.zip)
[3ds-Continuous_build.zip](https://github.com/EasyRPG/Player/files/8928226/3ds-Continuous_build.zip)
[PSVita-Continuous_build.zip](https://github.com/EasyRPG/Player/files/8928227/PSVita-Continuous_build.zip)
ry)

Game Files
https://www.freem.ne.jp/win/game/17735

#### Describe the issue in detail and how to reproduce it:
- Arrow key(+ WASD) does not work properly on custom menu. (ex: The menu that comes out wen you press the 'X' key)
Only the left arrow key works (Can be checked by navigating to the 'items' tab at the top of the menu).
- The 1, 2, 3 keys does not work.
This game uses the Number keys on QTEs and Puzles, But the number keys does not works.
-----

**Comment by fdelapena** [comment]
Thank you for the bug report. It seems to be the same issue as #2614.

**Comment by fdelapena** [comment]
Hi @Th10Lover, the game uses RPG Maker 2003, likely migrated from RPG Maker 2000, because RPG Maker 2003 directories are not being used so the heuristic detector likely fails due to this.

As a workaround, please  add the following command line when using PC version:

```
--engine rpg2k3v105
```

Demonstration of working menu allowing to move to the 3rd selectable position:

![Captura desde 2022-08-03 12-47-04](https://user-images.githubusercontent.com/174885/182686032-b6699911-4dc8-451d-b60b-c28af28227d3.png)

I don't know if other, non-PC platforms allow passing arguments to Player by setting them on launcher somehow.

**Comment by carstene1ns** [comment]
The logfile says it detects 2k through heuristic. This means it is the first game we encounter that is made in 2k3 and does not use any "advanced" features from it:
https://github.com/EasyRPG/Player/blob/3842fd37ea246c314e6a4ded455506ef246730a0/src/player.cpp#L729-L746

**Comment by carstene1ns** [comment]
We will track this in #2614 further (since it is older). Thank you for the bug report!

**Comment by fdelapena** [comment]
Hello @Th10Lover, in case you missed the original issue updates, this got fixed on the continuous builds. Check https://github.com/EasyRPG/Player/issues/2614#issuecomment-1504756417 for details.
