### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by th0rig** [EasyRPG/Player#2894]
#### Player platform: Android
This is more of Feature request than issues can you add more button for virtual because some games need more button than ok and cancel that is a and b like shadow seeker tanks for the hardwork

**Comment by Mimigris** [comment]
> #### Player platform: Android
> This is more of Feature request than issues can you add more button for virtual because some games need more button than ok and cancel that is a and b like shadow seeker tanks for the hardwork

Make sure to use the latest version of the player, but you can change the buttons that you can use on your touchscreen in _Settings -> Controls -> Manage the button layout_ and then vertical or horizontal depending on how you play.
So this is not really a feature request since it's already available.

**Comment by Ghabry** [comment]
You can also access this setting while the game is running by touching the burger menu button.

**Comment by th0rig** [comment]
Ok thanks for the info
