### ISSUE TITLE
Font filetype priority, font rendering issues, ignoring bitmap fonts contained within .ttf / .otf

### ISSUE THREAD

**Issue by Goburinbro** [EasyRPG/Player#2953]
#### Attach files (as a .zip archive or link them)
* Test Project is attached.
* All necessary fonts are included in the \Font folder. You may copy/paste/delete/etc them and rename them as needed to make the necessary observations.
* A version of the .ttf font with a bitmap in it is included as well. You can verify that a bitmap font is in there with FontForge or some other font viewing/editing tool.
* A recent release of RPG_RT.exe Maniacs Patch is also included if you need to launch the game that way for observations.

![image](https://user-images.githubusercontent.com/86999721/231453334-50c4c022-d147-4203-adfc-f0f8bb5b1d1c.png)
![image](https://user-images.githubusercontent.com/86999721/231453569-de088249-fd78-40c0-8605-abf2b04e0788.png)

#### Describe the issue in detail and how to reproduce it:
* EasyRPG player renders all fonts for screen text & Show String Picture 100% fine when a .fon is used.
* EasyRPG player does not render fonts correctly for Show String Picture when a .ttf or .otf is used.
* EasyRPG gives priority to .ttf or .otf if multiple fonts with the same name are present in the Font folder (if Mother 2 12px.fon and Mother 2 12px.ttf are in the Font folder together, it will ignore the .fon version).
* EasyRPG player ignores bitmap fonts that are contained within .ttf / .otf fonts and simply renders text based on the font outlines instead of using the bitmap (which should display correctly since a .fon on its own does).

[Test Project.zip](https://github.com/EasyRPG/Player/files/11211117/Test.Project.zip)

**Comment by Ghabry** [comment]
As Maniac Patch did the "lazy" solution and calls into WinApi the problem is to map the metrics correctly exactly like Windows does it.

Some insights are given by Wine: https://github.com/wine-mirror/wine/blob/master/dlls/win32u/freetype.c#L2394

There is different handling depending on if it is Scalable in that case a VDMX table is used. That table is unsupported by FreeType.

Example how to extract it using Chromium:

https://android.googlesource.com/platform/external/chromium_org/third_party/WebKit/+/1e20218/Source/core/platform/graphics/chromium/VDMXParser.cpp

Also notable is that it disables scaling for bitmap fonts. Maybe this is the cause for our px/pt mismatch?

**Comment by Ghabry** [comment]
I will likely fix this for fonts with bitmaps first and think about proper ttf scaling later as bitmap is the more common use case right now.
