### ISSUE TITLE
Integrate external toolchains better

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#296]
- [ ] Add command line options to `configure` to compile for wii, gcw0, etc. or use CMake Toolchain files
- [ ] Set default flags, defines and variables, but allow user overriding
- [ ] Use macros to conditionally compile sources
- [ ] …
- [ ] Clean up `builds` folder, remove Makefiles

more to come

**Comment by carstene1ns** [comment]
After #1365, this should now be done with CMake. :+1:
*(Wow, has been 4 years already)*

**Comment by fmatthew5876** [comment]
How about this one @carstene1ns ?

Are any of these still relevant after all the build system changes we've had recently?

**Comment by Ghabry** [comment]
Not really, we still use the same, old Makefiles we always used (look in the builds folder) for anything that is not Windows, Linux, emscripten (Web) or OSX.

The only progress we ever had here is that Windows is now buildable via CMake.

The next one will be libretro via CMake and these changes are a good base for further work (because they make the CMakeLists more generic).

**Comment by Ghabry** [comment]
No idea if this is relevant for us. Solution for one 3DS-CMake problem: https://github.com/devkitPro/pacman-packages/pull/41

> I noticed that all the undefined references came from 3dsx_crt0.s and that they were defined in libctru.

> Adding -L/opt/devkitpro/libctru/lib -lctru to the CMAKE_EXE_LINKER_FLAGS fixed the issue for me.
(> I'm saying this because the issue came back when you re-added set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -specs=3dsx.specs") and I finally figured out what was causing it.)

**Comment by Ghabry** [comment]
With CMake 3.20 a new cli option "presets" was added.

This allows reading presets from a json file (https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html).

Could be useful to make the CMake invocation less verbose and reduce redundancy in jenkins when we use specific ci-presets.

**Comment by carstene1ns** [comment]
I consider this one fixed with #2627.
