### ISSUE TITLE
Libretro core: Midi files are incorrectly stopped

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#2976]
#### Name of the game:
Yume 2kki & [No. 23 Corpse Casino](https://viprpg2021s.kenkenpa.net/no23.html).

#### Player platform:
Windows, libretro core, 64 bits continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
When playing on Yume 2kki with the libretro core of the Player, the music of Graveyard World is incorrectly stopped when another music should be played after playing it. Instead of stopping, the music continues until a midi file is played and will even play while another wav or mp3 is being played (returning to the title screen or to the game browser will not even stop it). This issue may not happen every time and does not seem to be present on the non libretro build of the Player.
You can find the midi music in question below, and you can see the issue in this [video](https://youtu.be/FEg44q_xEoU). 
[ym2-19_kuruwasiimonohahaieguru.zip](https://github.com/EasyRPG/Player/files/11345729/ym2-19_kuruwasiimonohahaieguru.zip)

**Comment by Ghabry** [comment]
So it is really only this one song? Weird

**Comment by Mimigris** [comment]
> So it is really only this one song? Weird

Just did a bit more testing with Yume 2kki and it seems to happen with every midi file that I could test, with the midi playing being more or less subtle. I also had this issue with some of the midi from [No. 23 Corpse Casino](https://viprpg2021s.kenkenpa.net/no23.html) (I didn't check which files were affected).
Weirdly enough, I was not able to reproduce this issue in the TestGame 2000. Maybe there is something different with the midi files and how I asked to interrupt them?

**Comment by Ghabry** [comment]
the problem is my "heuristic" to detect if RetroArch lost focus and to stop MIDI playback in that case. There is a bug that continues the Paused MIDI at the wrong situation. I cannot figure out a way to solve this so I remove the heuristic for now.

This means the MIDI will continue playing while RetroArch is in the background when using the native midi device. I cannot fix this properly.

The real issue is here that there is no callback to detect if RetroArch lost focus. There is an "enable audio" callback but it is not called when losing focus ¯\\_(ツ)\_/¯.
