### ISSUE TITLE
Transition flashes blue on certain platforms

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2981]
via mail:

Hey whenever I use easyrpg on anything, like my wii, my switch, my 3ds, they all flash a blue screen whenever the app changes its scene, like when opening a door in a game or changing between menus when opening easyrpg. Is this fixable or is there a patch? Or is it always gonna be like this? Thanks for your time

**Comment by Mimigris** [comment]
I can confirm that this issue is present on the 3DS version, I have several screenshots of this issue from when I tested to do some tests on it. For example:
When trying to display a transition in the TestGame
![Bluetransition](https://user-images.githubusercontent.com/108797333/236648470-d8976b4a-9da6-446d-b941-1807a9204202.png)
When opening the menu in a game (e.g. Someday)
![Bluetransition2](https://user-images.githubusercontent.com/108797333/236648472-7bafe2d6-b2bd-4c94-922b-bdfa252ce675.png)
_Note that the colours may not be entirely accurate due to how I took these pictures, but this issue is indeed present._

**Comment by Ghabry** [comment]
Cannot figure out what why this is broken. Looked at it for over an hour.

When replicating the code at the computer it works fine so it must be something really specific :/

**Comment by kringlexd** [comment]
it seems this is happening on my 3ds again after it not happening for some time. the blue flash doesnt happen on my switch however, so I'm wondering if anyone else is able to test if this is currently happening on their 3ds as well.

**Comment by Mimigris** [comment]
I'm not able to reproduce it on my New 2DS XL and I tested with the continuous build, are you sure that you are on the latest continuous build and not on the version 0.8.0? (you can see the version in Settings -> License -> EasyRPG Player)

**Comment by kringlexd** [comment]
ah, i didnt realize vers 0.8.0 was not the latest one. After installing the continuous build and checking with a couple games, theres been not one blue screen, thanks
