### ISSUE TITLE
lcftrans: Entry map (CE Call) is not translated when using the "NewGame" option

### ISSUE THREAD

**Issue by florianessl** [EasyRPG/Player#3048]
When using the option "NewGame=1" to skip the titlescreen (and starting EasyRPG with --language parameter), the starting map is not translated. One has to press F12 & reset to get a translated version of the map.

**Comment by Mimigris** [comment]
> Correction: It seems some parts are translated, but the part that isn't (Custom titlescreen) comes from a common event call. A simple workaround might be to just copy all that over to the map.

I guess that it could be a duplicate or related to that: https://github.com/EasyRPG/Player/issues/2829
In the game I've mentioned, a Common Event containing text is set as a Common Event with a Parallel Process, and when loading first from a new game, the text from said common event is not able to be translated, it is only able to be loaded on second try or if a save that contains the translated lines is loaded (since the lines are saved in the save file).
