### ISSUE TITLE
[7th Stand User] Cannot use items which invoke skills when skills are sealed

### ISSUE THREAD

**Issue by Mike-U5** [EasyRPG/Player#3057]
#### Name of the game:
The 7th Stand User

#### Player platform:
Windows 10

#### Attach files (as a .zip archive or link them)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/12064753/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
When fighting the Alessi boss, characters cannot use items if EasyRPG is used. Or at least, they more often than not will fail to work. For example, the "UV Laser" or "Handgun" items fail to work. Absolutely nothing happens when they are used. The characters just lose their turn.

Something interesting to note: In this battle, the actors have the "Child" status which prevents them from using skills with a magic/attack rating of 0 or higher. (So, all skills)
I suspect that, due to some mistake, this prevents characters from using item-skills too. 

Edit: Looking at the editor show that the "Child" effect is reapplied every turn. If I remove this logic, the issue does not occur. Seems like the item-skill is incorrectly canceled when the "Child" state is **applied**.

**Comment by Ghabry** [comment]
Items that invoke Skills are implemented as Skills with Items attached (as they are more like Skills than Items). When a state is added the code checks whether the Skill is still usable and we do not consider if it is an item skill where these restrictions do not apply.

Though there must be something else wrong in our code because now the battle message is displayed incorrectly...

**Comment by Ghabry** [comment]
Correction: This empty message is not a bug. Same in RPG_RT *shrug*
