### ISSUE TITLE
A map crash occurs in environment Wii

### ISSUE THREAD

**Issue by LEESEOJn** [EasyRPG/Player#3185]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:Wii
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)
![KakaoTalk_20240119_140849567](https://github.com/EasyRPG/Player/assets/157088086/87ec19dd-7044-4fdc-8666-16e1d98af3f1)
![KakaoTalk_20240119_140847373](https://github.com/EasyRPG/Player/assets/157088086/74ea3e8c-a888-4752-a97b-c07d7d0d2ac1)
![KakaoTalk_20240119_140845346](https://github.com/EasyRPG/Player/assets/157088086/d3a556a5-24dd-45df-874a-59451d94ed1c)
#### Describe the issue in detail and how to reproduce it:
I've already run 'Wadanohara and the Great Blue Sea'(大海原と大海原), a game that is known to be fully running, in Wii's environment, but map crash occurs badly as shown in the picture.
I started by changing the running language and reinstalled the game or tried running a version of another language, and even though I reinstalled the emulator itself, nothing changed.
I just checked that it runs fine on Windows and Android, could you please fix that?

**Comment by Mimigris** [comment]
The issues that you are mentioning here should be fixed in the continuous Wii build of the Player (the continuous build of the Wii version should be available on the https://easyrpg.org/player/downloads/#snapshot-other page, in the `EasyRPG Player continuous builds` category, `Other` -> `Wii`).
While testing on my side, I was able to reproduce your issue on the version 0.8.0 of the Player by testing with the Japanese Reboot 1.01 version of the game, but not on the continuous build of the game, so there should be no issue if you try to play with the continuous build of the Player.
(Also, if you plan to play on Wii with the continuous build for now, make sure that your game is in a zip archive and that you are not playing directly from the folder of the game, otherwise you may encounter crashes when some music are attempted to be played)

**Comment by LEESEOJn** [comment]
Thank you. Screengore was a problem that solved by running with the .zip extension. Thanks to you, it was solved!
