### ISSUE TITLE
BGM mutes after BGM change, unmutable by clicking out and in the window again

### ISSUE THREAD

**Issue by Xenoras** [EasyRPG/Player#3186]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/13988176/easyrpg_log.txt)
[Save15.zip](https://github.com/EasyRPG/Player/files/13988177/Save15.zip)

#### Describe the issue in detail and how to reproduce it:
Sometimes after a BGM change (eg after map change or after a fight), the BGM is not audible. It appears to play on mute still though. You can unmute it again by clicking out of the window and back in.
The Savegame is in the Castle Map. When I loaded, the music was already gone. Just click out of the window once and back in. The music should continue. If you go out of the map and back in, the music is muted again

**Comment by Mimigris** [comment]
I've mentioned this issue in #2319 but it may be better to list it separately, thank you :+1:

It's an issue specifically tied to the use of the Native MIDI output on Windows, and only affects MIDI files.
What I wrote there, in short:
"Partially related so I'm adding it here, but exiting a game with a midi on the title screen and then reopening it from the game browser may have different results (lack of some instruments, incorrect volume of some instruments, lack of music...). This is not major since it will not continue past the title screen and that just putting the window of the game in the background and reopening it will work as a fix for a player. (Opening the settings menu on the title screen in said condition can also cause the issue to happen)."
Why I didn't noticed back then was that this issue also affects tracks that are played outside of the title screen.

**Comment by Mimigris** [comment]
For the content of your easyrpg_log.txt file, note that Fluidsynth and WildMidi are only optional methods of playing MIDI files (where the user need to manually add files to make them work, hence why it is listed there on your side) and are not related to this issue.

**Comment by Ghabry** [comment]
This appears to be some "race condition" when changing the MIDI. Sometimes the music plays, sometimes it doesn't. So likely depends on the state of the previous MIDI :/
