### ISSUE TITLE
Interpreter hangs when running "continue processing events" command after "move event" command execution on parallel interpreter

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#344]
How to reproduce:

1. Create a parallel event with a move event command.
2. On the same map, create an automatic event with a continue processing events command.
3. This command must be set after some behavior specific commands, like wait command or move event. Otherwise, after e.g. a show message will work fine (?).

Here is a [test case](https://fran.cr/owncloud/index.php/s/KHwW2DiMk4IZoz2/download) to verify this weird race condition.

Verified affected games: 
- Desolate City (initial cutscene)

**Comment by scurest** [comment]
Has this one changed, maybe? I couldn't find Desolate City (link please? :) but I don't think I got the hang in Rainbow Treasure (you don't mean this one,
![hang](https://cloud.githubusercontent.com/assets/11024420/6281193/2d7c5950-b881-11e4-8f4b-72f63418c358.png),
do you?).

RPG_RT will hang on the testcase if the movement command takes time to complete. Seems like it only goes through to the next message box if the movement route completes instantly, like a "Face Right" or an empty route or something.

**Comment by fdelapena** [comment]
Not sure if 8cb3d84 changed the behaviour of the test case but it is still hanging at least for Desolate City. Here is a link to the [Desolate City](https://www.sendspace.com/file/a8n0g5) game. The game is unreleased yet, but authors contribute with Player with bug reporting.

About the Rainbow Treasure image hang yes, the hang I was reporting is in this cutscene point, just after these "!" appear.

**Comment by scurest** [comment]
The hang with the ！ is actually unrelated: it's caused like this

1. a switch goes on
2. the ！ events' page condition is met, so they come into existence.
3. all the characters except Nickel jump and land
4. because Nickel is on top of the location of the bottom most ！, the game won't let her land (in `isLandable`, the first loop that checks whether there's an event at the same location won't go through) so she gets stuck in the air.

ec7f07de let's you get past that spot in the cutscene.

Thanks for the link for Desolate City, I'll look at it later.

**Comment by fdelapena** [comment]
Wow, neat find, I was guessing it was the same issue because this operation was using the "continue processing events" too and when removing some commands was continuing.

About Desolate City: recently Zegeri said the game may have some relation with the mirror event.

**Comment by scurest** [comment]
Confirmed it's the mirror event, just like in the testcase.

So I thought that maybe RPG_RT will run the whole movement event if it can before finishing the Move command, while EasyRPG only runs one move route command each frame.

So I made a quick test: run a move route like

    Face Right
    Face Up
    Face Down
    Face Left
    ... repeated a dozen or so times...

and in RPG_RT it completes in one frame so you don't see any movement, but in EasyRPG you see the event rapidly turning since only one command is run each frame.

So the solution I'm thinking of is to process move route commands in a loop like is done for event commands, and then then call this function from `CommandMoveEvent`. Then anything that completes instantly will come off the pending queue before the Move Event finishes.

**Comment by Zegeri** [comment]
f40d110 fixes this. Now let's check if it breaks other things.

**Comment by fdelapena** [comment]
After further testing since latest merges, this ProceedWithMovement bug issue regressed with current master :cry:.

**Comment by Ghabry** [comment]
Okay in that case I would priorities #646 for the next weekend. Is almost complete anyway...
Just need to fill the event-tests repo and adjust the code a bit to automatically execute over all that maps...
