### ISSUE TITLE
Vampires Dawn: Summoning doesn't cost soul stones

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#404]
Vampires Dawn: This game only allows summoning a 4th character via a spell triggered through the spell menu. Summoning such a guy costs magic (here: blood) and an item called soul stones. The magic isn't reduced.
Probably related to #403 

> Summon a servant (e.g. Golem) or use a transformation (e.g. into a wolf) doesn't consume blood (resource). 

Reported by Darkztar

**Comment by Darkztar** [comment]
I have to correct this bug report: 

Normally a summon should take blood and soulstones. Now it takes only Soulstones and no blood.

This is very heavy in combination with [url=https://github.com/EasyRPG/Player/issues/402]#402[/url], because after each change of the map the summon is done again and you lose every time Soulstones.
