### ISSUE TITLE
[Deutsch/German] Meldung eines Bugs

### ISSUE THREAD

**Issue by Soranela** [EasyRPG/Player#650]
Hallo, 
Im Spiel "Unterwegs in Düsterburg" stürzt das Spiel ab sobald man sein eigenes Haus in Düsterburg betritt , nach der Trance Sequenz wenn Julie zu seinem Wassernapf läuft .. jetzt habe ich keine Ahnung wieso das so ist aber in der Appbeschreibung auf Android im PlayStore steht das man hier Bugs melden soll  . :)

**Comment by Soranela** [comment]
Hello , fixed this bug by removing the "wait for player movement" code when opening the game in the rpg maker .
seems like theres a problem causing to make an event walk more steps than programmed ...
the version works fine on PC:

**Comment by Zegeri** [comment]
Could you tell us the ID of the map with that event?

**Comment by Soranela** [comment]
Sure man! ID: 0062 > EV0013 > Page 4.

**Comment by Zegeri** [comment]
Thank you.

For the developpers: Run the player with --test-play --start-party 1 --start-position 15 9 --start-map 62 and activate manually through the debug screen the switch 286 (erstes mal a), to start the cutscene that ends with this bug.
This bug can be replicated in a test case with a non-empty auto-starting event and another event with a self-movement like Walk horizontally. The player won't be able to move (because of c5093e56) but the event will incorrectly do its move route.

**Comment by Ghabry** [comment]
@Soranela 
Thanks for reporting. The bug got fixed by one of our developers and the new version will be on google play in the next hours.

**Comment by Soranela** [comment]
Nice, thanks a lot! 
Since you are all  so fast and friendly i'll make sure to report any other signifant bug too :+1:
