### ISSUE TITLE
Android icudata lacks encodings

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#698]
The following selections in the android gui generate bad encoding errors
Is the icudata used incomplete?

Windows-936 Simple chinese
Windows-950 traditional
Windows-1254 turkish
Wndows-1257 baltic
Ibm 449 p110 1999 Korea

**Comment by fdelapena** [comment]
My bad, it is incomplete. I forgot to include some encodings. I based on some reader_util data which does not have Chinese, Turkish or Baltic substitutions because Chinese encodings does not need to force conversion name (it finds the proper one already) and Turkish and Baltic can't be detected automatically by ICU (only by manual setting). About Korean (ibm949-P110-1999) probably remained a test for changing it into windows-949-2000 or another encoding. Let's fix this.

**Comment by fdelapena** [comment]
Updated icudt56l in the same URL, please try again.
