### ISSUE TITLE
Uniform pixel size in full screen mode

### ISSUE THREAD

**Issue by BlisterB** [EasyRPG/Player#720]
Hi everyone !

This issue can be observable in all plateforms (including the android port) : when a game is in full screen, the aspect ratio is not respected.
It causes several problems : 
- The render is not clean : characters' eyes don't have the same size etc.
- More problematic : scrolling seems to be laggy (at 60 fps) due to this ratio not respected. Lot of people thinks this is not a really 60 fps because of that.
- It affect everything in movement : pnj, water tiles etc.

It would be a big improvement if we could find a solution :).

**Comment by fdelapena** [comment]
This feature exists in 2k3 1.10+, all pixels have the same size on full screen, scaling to the max pixel size available.
E.g. on a 1920x1080 screen would fit a 1280x960 (4x pixel size) game screen size, but not a 1920x1200 (5x pixel size) because the height is larger than the available.
It could be checked by w=320*n and h=240*n, and both must fit to the available screen size (beware of existing menu bars in some devices).

**Comment by Ghabry** [comment]
I have code for this on my hard disk. In the branch for the portable touch UI.

When you just tell SDL "I want 320x240" then it rescales for you but you can't render in the black Areas outside of this 320x240...
So my fix is to just create a texture with the size of the window and then render the EasyRPG 320x240 on it via a rescale... That way you can render on the black area and do other nice things like pixel aspect ratio ;).

**Comment by fmatthew5876** [comment]
So for touch UI to work you have to render to the entire screen? You can't create a viewport?

`SDL_UpdateTexture` takes a rect. So could we not make the texture the smallest multiple of screen size that fits 320x240, and then copy our bitmap to the texture at it's center. And then render the texture like normal?
