### ISSUE TITLE
Space Funeral: Unrecognized format when playing mp3

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#721]
Reported by a user on Google Play.
I wouldn't care about noise when playing MP3 but "Unrecognized format" warning is new :O.

Not tested yet.

**Comment by carstene1ns** [comment]
The mp3 files have additional padding before the magic number, so the detection fails.
I do not know if this is some kind of protection and a patched harmony is used, but the files seem valid for playing in mpv at least.

[![hex](http://picload.org/thumbnail/wrwrrii/20160111115312_916x573.jpg)](http://picload.org/image/wrwrrii/20160111115312_916x573.png)

**Comment by fdelapena** [comment]
`Mix_LoadMUS_RW()` uses magic numbers to detect file formats regardless of their extension (e.g. used for renamed files as .wav). A possible fix would be retrying when the function fails and retry with the existing `Mix_LoadMUS()`, which tries to play based on the file extension instead.

Unfortunately, `madplay` (libmad music player) does not support them, so I guess they won't work even with the `Mix_LoadMUS()` call:
```
$ padsp madplay beginnings\ -\ ruth\ white.mp3 
MPEG Audio Decoder 0.15.2 (beta) - Copyright (C) 2000-2004 Robert Leslie et al.
          Genre: Blues
error: frame 0: lost synchronization
output: write: Connection reset by peer
```

MP3 from other games work as expected with `madplay`.

As a side note, `mpg123` (the music player from the alternate LGPL library) worked flawlessly with all MP3 files.

**Comment by carstene1ns** [comment]
It might be true, that some players will skip the empty bytes and find the real file header¹, but for them it is not about compatibility with this specific file type, it is about supporting all incomplete/broken files to a degree that makes most out of it. Then madplay just never intended to support such thing.
In this case, all files have the same 'padding' (= fake header), so this likely is intended.

Rather than implementing some workarounds that 'might work'² and are for one specific game, I would tell the user that this game needs some additional setup in the compatibility list (to be written).

A (stupid) comparison: If someone complains that Player cannot open TST:T, would you rather point to the wiki entry about it (that explains how to get it to run) OR would you like to implement some lmt decrypter for only this game in Player?

¹) mpv says `[ffmpeg/demuxer] mp3: Skipping 417 bytes of junk at 0.`, afair it loads at least the first 2 kb or so to search for a valid stream…
²) sdl2_mixer is modular and let's the associated libraries do the heavy lifting, we cannot really decide to use mad, smpeg, mpg123 or maybe someting entirely different without explicitly using it's api and giving the buffer from the library we choose back to sdl2_mixer. it is a mixing library not an all-in-one solution.

**Comment by Ghabry** [comment]
Okay so let's fix this upstream with a patch to SDL_mixer. Then MP3 will work in 2 years with Mixer 2.0.2 \o/

**Comment by Ghabry** [comment]
FYI. The PGE-Project uses a patched SDL_mixer version, maybe some patches are useful?
https://github.com/Wohlhabend-Networks/PGE-Project/commit/a90059ae32a0792d2c47f2b817c616fcef50ed20

They also have a fix chunk mp3 playback patch. But my patch only alter 3 lines and is simpler ;)
