### ISSUE TITLE
Write smarter RTP translation table logic

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#802]
Maybe use [`std::unordered_multimap`](http://www.cplusplus.com/reference/unordered_map/unordered_multimap/).

**Comment by Ghabry** [comment]
One issue is that different translations map the same string to different assets. This could be solved by matching all RTP-translations against the RTP directory file list and the one with most hits is used as the reference RTP.

What is also missing is that N-to-M mapping. Currently it's Japanese to Other, instead of "Prefered one" to All.

**Comment by rohkea** [comment]
An example case that should ideally be handled by the new code.

If:

* RTP is Don Miguel’s RTP 1.32 (contains both ‘Basis’ and ‘World’),
* the game is likely to use Advocate’s RTP or Official RTP, i.e.
    * the engine is RM2k3 with a codepage different from Cyrillic, or
    * the engine is an official RM2k,

Then:

* World in the game should be mapped to Basis from RTP, and **not** to World in the RTP.

**Comment by Ghabry** [comment]
What I would also propose is:

Scan the RTP folders and then determine how many % of a RTP overlap with our internal table (hopefully 100% ;)) and then use the detected RTP as the reference for lookup.

But for this we would need a different data structure first to make this more efficient. Currently we have "Any -> Japanese". A table structure like in the Wiki would be better:

1 Line with one RTP per column:
["システム", "System1", "system"] e.g.

This way you could easier do Any-To-Any mappings.
