### ISSUE TITLE
Skills won't do damage

### ISSUE THREAD

**Issue by Zekario** [EasyRPG/Player#845]
I'm trying to do skills in RPG Maker 2003, but whether or not they work is complete magic. Most of the time, the skill just does 0 damage, but sometimes it just straight up isn't usable in battle.

**Comment by Ghabry** [comment]
Could we have a test case?

Name of the game +
 a savegame next to a battle where this can be reproduced +
 Which skills fail

**Comment by Siltala** [comment]
I think I am hitting this bug in Embric of Wulfhammer's Castle. In a battle against an anti-paladin and a horse, some of the enemy's attacks seem to do 0 damage. Some player attacks against the anti-paladin also fail (i.e. do zero damage) but others work. The horse, however, seems to be immune to everything I throw at it and thus is completely unkillable. I'm confident this is a regression, since I had no issues with this encounter in some previous version.

* Game download: https://aeresland.net/EmbricDELUXE_2.2.2.7z
* Savegame: https://www.heavylobster.com/files/Save04.lsd

To get to the problematic encounter, just take one step west.

**Comment by Siltala** [comment]
Whoops, I think you can disregard the above message. I retested latest git (previously tested with the 0.4.1 release) and my problem seems to be fixed there.

**Comment by carstene1ns** [comment]
@Siltala: Yep, there was a bug that snuck in right before the release and has since been fixed.

**Comment by carstene1ns** [comment]
@Zekario: Can you please retry with a build from current development snapshot?
You can find it at the bottom of this page for most platforms: https://easy-rpg.org/player/downloads
Please reopen, if the issue persists.
