### ISSUE TITLE
PeuterisGrey: heroine makes double steps

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#872]
[game download](http://s000.tinyupload.com/index.php?file_id=35755637109549384388), [emscripten](https://easy-rpg.org/play/index-master.html?game=peuterisgrey)

This game uses some common event to check for collisions etc. and has a sideview jump-n-run like feeling to it. However, the heroine seems to always run/makes double steps:
![shot](http://picload.org/image/rgdlddoo/screenshot_7.png)

Savegame to skip the intro: [Save01.zip](https://github.com/EasyRPG/Player/files/233599/Save01.zip)

**Comment by Zegeri** [comment]
Here's a brief explanation: This is caused by the way we handle Game_Character::remaining_step. In DynRPG, this same field is called movementFramesLeft. This field goes from 256 to 0 during any movement.
In RPG_RT, right after a move command is executed, its remaining_step is reduced within the same frame. While in Player, it's first reduced in the next frame. For that frame, PeuterisGrey scripts think the hero isn't moving and causes the double step.

**Comment by Zegeri** [comment]
3f0ce4e2f4 fixes the double steps, but it doesn't fix the weird scrolling.

**Comment by Zegeri** [comment]
This can be closed. @scurest fixed this with b3026d2a4b8.
