### ISSUE TITLE
Static binaries for x86

### ISSUE THREAD

**Issue by radialapps** [EasyRPG/Player#904]
I searched high and low, but could not find any static binaries for x86 (Linux). Can someone please create one from the latest stable branch, so that it would be easy to test (I have multiple 32 bit systems but none of them have internet access, which makes it impossible to install easyrpg) (btw, sorry for creating an issue just for this, but I couldn't find a better way to say this. In case there is, can someone please delete this and tell me?)

**Comment by Ghabry** [comment]
We have the Player at the OBS: https://software.opensuse.org/download.html?project=home%3Aeasyrpg&package=easyrpg-player

**Comment by radialapps** [comment]
I tried installing easyrpg player using OBS on ubuntu 12.04 (which I know it doesn't list, so I used the 14.04 repo), but it fails, citing that liblcf is not present in the repository. Anyway, I meant a statically linked binary, so that it would be really distribution independant.

**Comment by carstene1ns** [comment]
> so that it would be really distribution independant.

![nope](http://i.giphy.com/USNlL9p2fxY6Q.gif)

It is not really that easy. There are a lot of things that can break when you want to have that.
For example api incompatibility, different libc and processor optimizations (like sse) to just name a few. The 64 bit build we provide is not meant to be used in production or something, it is merely for testing without needing to get the dependencies and therefore mostly used by developers.

About the OBS package: I did not enable this Ubuntu version, because it is rather old. There is a new LTS release for quite some time now. That being said, liblcf is also provided in the repositories, so it should be able to find it.
Also you may succeed in installing the debian packages instead, however this is really not recommended.

What about just building the Player yourself? It is not really complicated:
https://easy-rpg.org/wiki/development/compiling/player/autotools
