### ISSUE TITLE
3DS Jenkins build not successful

### ISSUE THREAD

**Issue by gnmmarechal** [EasyRPG/Player#918]
I'm not sure where to report this.

https://ci.easyrpg.org/job/player-3ds/

No successful builds for a while now.

**Comment by carstene1ns** [comment]
There is already an open pull request to resolve this: https://github.com/EasyRPG/Player/pull/915/commits/ada103958cc758451eb0699c5036b2065e330581.
However, this needs a toolchain rebuild first.

**Comment by Ghabry** [comment]
The problem is that Rinnes cSND code needs functions that are not available in the latest ctrulib release (which was in January), so we use the latest code from the ctrulib repo.
But they refactored there code some weeks ago and this broke our code.

Best thing would be when ctrulib gets a release again... :(

**Comment by Rinnegatamante** [comment]
huh, i had not noticed such modifications in csnd.
Going to patch them now so.

**Comment by Rinnegatamante** [comment]
Mhhh i cannot see any modification in csnd wrapper. Anyway i managed to compile the whole project with latest ctrulib. If needed i can make a pull request.

**Comment by Ghabry** [comment]
Well it was DSP or CSND which lacked a function but this was months ago (in February), can't remember, but was some audio stuff. That was the initial reason to use latest ctrulib git and not the 1.1.0 release.

The building is already fixed, we are just currently a bit slow in recompiling the toolchain because it's summer. Give us a week or two :)
