### ISSUE TITLE
葬 (Sou): Interpreter hangs after entering to new map

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#927]
__Name of the game__: 葬 ([Sou](http://frog4151.web.fc2.com/sou/)) v1.03. [Download](http://www.vector.co.jp/download/file/winnt/game/fh624534.html). Contains Japanese files, unpack with `unar`.

__Player platform__: Any

__Attach files__:
 - [Savegame](https://github.com/EasyRPG/Player/files/357258/Save01.lsd.zip).

__Describe the issue in detail and how to reproduce it__:

Open the savegame and go downstairs to the next map. Then it won't be able to move.
The game menu showing the items held (Ib style) won't be accessible either, so it looks interpreter related.
Reported by モノ via Android app email bug report.

Note: This was already hanging before merging recent character movement fixes.

**Comment by Zegeri** [comment]
This is caused by an auto-starting event that takes 1 frame to complete. In easyrpg, other events aren't allowed to run their self movements. But in RPG_RT, they can. 
There's a deeper problem behind this: auto-starting events that take more than 1 frame shouldn't waste a frame to loop to their beginning (just like repeating move routes). Fortunately, these two issues can be fixed together quite nicely.

94cbf21ea2f should fix this.
