### ISSUE TITLE
Pom Gets Wi-Fi: Interpreter stops after a "Stop!" message

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#937]
The issue title is pun intended, but it really happens :laughing:.

[Game](http://rpgmaker.net/games/5441/). [Savegame](https://github.com/EasyRPG/Player/files/367408/Save01.lsd.zip).

To trigger the halt sequence, press the decision key with the dog or with the door. After some dog advice and a transition, the door will be opened and a dog will say a "Stop!" message and interpreter halts. Some dogs should appear and start a battle instead. Earlier master versions were working there, so this is a regression.

**Actual Bug**
When a event that is "Waiting" collides with another event the wait timer reduces faster (depending on how many are colliding), so when one collides the wait countdown is twice as fast.

**Comment by scurest** [comment]
[Cause](https://github.com/EasyRPG/Player/pull/936/commits/94cbf21ea2fd768ba541a32fee8e82a0e1d5ffe5#diff-80d5e57884c2e60d4f4084c5ab5ed79fR479).

**Comment by Zegeri** [comment]
Here's the explanation: In the map 21 (The Gate Open2), the event EV0004 tries each frame to walk where EV0005 is. The move route of EV0004 is skippable. EV0005 has a parallel event with a ProceedWithMovement.

In EasyRPG, EV0004 will try to walk where EV0005 is. Because of #884, EV0005 runs its interpreter early, executes ProceedWithMovement and, because EV0004 is still moving, doesn't continue. After that, EV0004's movement fail. Because it's a skippable move route, the move route ends.

In RPG_RT, things go the same way but after all that, **EV0005's interpreter gets updated a second time**. This time, EV0004 doesn't have an overwritten move route, so it passes the ProceedWithMovement command.

I'm not sure in what circumstances does an event get update twice.

**Comment by Ghabry** [comment]
In the meanwhile we know that it's the collision which causes this behaviour.

As a notice for the laaaaaaaate future when the editor is ready: The Player should offer for EasyRPG games a "Engine: EasyRPG" mode which does not emulate such bugs. ;)

**Comment by carstene1ns** [comment]
This one has been broken in #1601. Resetting milestone.

**Comment by fmatthew5876** [comment]
> In RPG_RT, things go the same way but after all that, **EV0005's interpreter gets updated a second time**. This time, EV0004 doesn't have an overwritten move route, so it passes the ProceedWithMovement command.
> 
> I'm not sure in what circumstances does an event get update twice.

This is still broken in #1687 

From Zegeri's comment above. I believe this is likely due to "PreUpdate" not being implemented correctly yet for teleportation.

**Comment by carstene1ns** [comment]
Broken again in #1628.

**Comment by fmatthew5876** [comment]
So here is a test for this

1. Setup 6 events like this:

| Tile | Tile | Tile | Tile
| -- | -- | -- | -- |
| | EV02 | | |
| EV03 | EV01 | EV04 | |
| | EV05 || EV06 |

EV01 parallel  `Var1 + 1`
EV02 parallel `OpenSaveMenu`

| Save | Var1 | EV01 stop_count |
| -- | -- | -- |
| 1 | 1 | 1 |

2. Now change EV02, 3, 4, and 5 to custom move types, all trying to step into EV01

| Save | Var1 | EV01 stop_count |
| -- | -- | -- |
| 1 | 5 :exclamation: | 1 |

Conclusion:
----------------

The parallel interpreter that runs in an events update loop ignores the `processed` flag and always runs every time a collision happens.

**Comment by fmatthew5876** [comment]
This is now fixed yet again and hopefully for good in #1687
