### ISSUE TITLE
Embric of Wulfhammer's Castle: Bugs with climbable wine causes the Duchess to face wrong direction

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#960]
This is a fairly minor, and rather amusing, at least in my opinion, bug:
The game has a vine you can climb. When you climb down said vine, it's graphically represented by the duchess walking backwards. In Player, if you don't stop walking after climbing down, the Duchess will keep walking backwards, while in RPG_RT she correctly turns around.

Videos illustrating the issue:
* Vine behavior in Player: https://www.heavylobster.com/files/embric_moonwalk.mp4
* RPG_RT: https://www.heavylobster.com/files/embric_no_moonwalk.mp4

Furthermore, it's also possible to 'walk forward' when climbing down in Player; try climbing down the vine from above to see this. In RPG_RT, the Duchess turns around when climbing down also.

* Game download: https://aeresland.net/EmbricDELUXE_2.2.2.7z
* Savegame: https://www.heavylobster.com/files/Save03.lsd

The problematic vine is directly north from the savegame's location.

**Comment by carstene1ns** [comment]
This is done using 4 events that apply a custom move route with direction fix. Seems like the flag is not applied (yet).

![events_screenshot](https://picload.org/image/rroooopd/shot4upload.png)

1. `Direction Fix OFF`
2. `Turn Up; Direction Fix ON`
3. `Turn Up; Direction Fix ON`
4. `Direction Fix OFF`

**Comment by carstene1ns** [comment]
This is actually a regression since 0.4.1 and likely caused by some move route refactor.
if you hook into [`Game_Character::Move()`](https://github.com/EasyRPG/Player/blob/fd5ea0eff6d4232aef01e120df0bc1463d64ce8f/src/game_character.cpp#L446), you will see the `IsFacingLocked()` condition is only triggered when you shortly release the arrow key you pressed before (i.e. down or up in this case).
