### ISSUE TITLE
Android: Legacy menus should be replaced with something more modern

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#982]
@BlisterB 
I think you should also take a look at the layout intent and the player intent now that the compat module is usable.

A user on a Samsung Galaxy Note S4 reported now, that for her the legacy menu at the bottom opens, but not completely. Only the first two options are available (Reset and Add button).
The menu seems to be half broken on many devices -.-

Is it possible to replace that legacy menu with a "swipe out from the left"-menu, like is used in the game browser, on newer APIs?

**Comment by ItsSchoko** [comment]
One minor problem that could occur:
A user may have the d-pad near the left side of the screen and starts moving his/her thumb from a "walking left" state to "walking right", which opens the navigation menu/game menu.

Therefore, the game menu should be pinned (there's an attribute for it) and only open when the user hits the backbutton or a custom menubutton:
![easyrpg_issue_982](https://cloud.githubusercontent.com/assets/17786862/17516647/0ba39daa-5e40-11e6-9d30-cdc0e14560f9.png)

**Comment by BlisterB** [comment]
I wanted the avoid the "menu" button (another visual information distracting from the gamescreen) but it seems that it will be a necessity. Thank you Samsung.
Combine it with a "swipe" menu like in the game browser is a good idea Ghabry : you click on the menu, it make the same menu appear at the left. No "miss click" possible.

I'm interested in dealing with this issue but I might run out of time, I'll try to inform you about it.

**Comment by Ghabry** [comment]
That's fine, the mob of angry  samsung s6 users is not that huge yet :D

**Comment by ItsSchoko** [comment]
@BlisterB: As my Mockup shows (#925), it only distracts when you have it fully visible, so I gave it an alpha value of 0.3.
You are still able so see it, but it's not too bright and it's on the same position as the standard menu button, which should help each user to realize what will happen when they touch it.
The 4:3 ratio of the games also helps, because there's a lot of black on the sides (landscape view), so no intrusion to the actual game canvas.
As I was planning a new UI a couple months back I also though about such things, which led to lowering the alpha value.
In the end it's not a bad move to have a button in the left upper corner, because it holds important features, which should help the users to find their way inside the application.

PS.: Also good news: By the end of the month, I will have time so finally start with the polishing process, so I should be able to provide a ready-for-gaming version.

**Comment by Ghabry** [comment]
Looks like this affects any Samsung user on Android 6.0, a S5 user just reported the bug, too >.>

**Comment by BlisterB** [comment]
I will be able to start to work on this in one week. This shouldn't be a big deal, I maybe will have to increase the maximum API compatibility. But this is not a problem anymore

**Comment by Ghabry** [comment]
The last rating (5 stars) from an Android 2.3.3 user was 2 weeks ago btw xD

**Comment by BlisterB** [comment]
Hahahahaha, Android.
I intend tu use a Drawer Layout, wich is (thanks to the support library) supported until API 9. So this should be good. In reality it's probably possible to make the actual Gamebrowser available for every API.

**Comment by BlisterB** [comment]
I actually have made some adjustments and the new Gamebrowser is available for API 10. Well, that could lead to a drastic code clean.

**Comment by ItsSchoko** [comment]
Really, you want to go that low?
When I started with the new UI, I was frustrated when a lot of features were not supported.
It's just a pain in the a** if you have an awesome idea and the API level won't make it possible.

**Comment by BlisterB** [comment]
I don't understand some of your messages @ItsSchoko , are you planning to just drop the whole actual system to replace by yours?
Besides, some of our user still use API 10 as said Ghabry, no need to upgrade the minimum API as we can support a lot of features with Android Support Libraries.

**Comment by ItsSchoko** [comment]
My goal is to create a modern looking UI for Easy RPG to minimize usability issues that occur now and then.

It's not about to always use the highest API. When I started with my stuff I talked to Ghabry which API level is prefered.
So I'm already using the support lib, but there are some design features which require a higher API Level and won't be used by older versions.
I will figure out a way to reach 10, but some features will only be available to newer devices.

Minor stuff that drove me crazy while testing on older APIs, for example: white backgrounds and wrong text color. ;)

**Comment by BlisterB** [comment]
Huu okay.
Because the project is a Free Software based on work in group, I can just highly suggest you to improve the existant instead on totally erasing it. For example you could do cool things on the Player activity or on the InputLayout system which is still a little primitive, instead of spending time to remake the Gamebrowser and the Preferences activities which are now in a satisfying state, and more important in a relatively clean code.

**Comment by ItsSchoko** [comment]
It's about polishing and showing that Easy RPG can look as awesome as it's core features are.

The Problem would be: If I would already be working on it, we would be working on the same issue at the same time, which would suck.

It's not about writing everything new, it's about taking the good things and improving them.
Let's take that alternative tile view, which you introducted:
You had the same idea and delivered code, which I will rely on, so I can focus more on the UI part.

We just have a different view on where we are statisfied with certain elements.

**Comment by BlisterB** [comment]
Well, I don't say it in a mean way at all, but I didn't understand what you want to do again.
Can you precise the exact nature of what you want to do? In a issue ticket for example? So we can talk about and make you not waste some time, and not waste mine too by distributing the work for example.

Because for example you talked about making the theme black yesterday, I personally oppose to that as I find the current one actual really cool and put a lot of time in it. That would be not cool if you just pass after my work to just swap the color because you prefer dark themes. Besides, proposing to swap theme in preferences could be cool, but would make the app heavier for user and less maintainable.
In your mockup you also show a tab in GameBrowser permitting to sort games by RPG Maker version, this is currently not advised to do so because you would have to parse the .ldb, which would take to much sys call and would make the app less responsive.

My idea is not to stop you working on the project, it's quite the reverse. It's just that if you want to modify a lot of things, we should talk about it before, to make a certain consensus and not wasting time to anybody.

**Comment by ItsSchoko** [comment]
Yesterday... a black theme? Where? I can't find anything.
My mockup was an adoption of the - back then -  latest theme, of course when I do such things I also  have a light theme in mind, so users can choose what they prefer. It's just an out of date example, while the downloadable APK already had a different, but also dark, UI.

The Tabs show "Recently Played", "All Games" and "My List" which indicates an idea, why Tabs could be a solution for something like a fav-list-system and also means nothing if such an idea gets dropped.
- Off-topic: When it comes to support more RPG Maker versions - I would suggest such a thing, because more users can throw away the other interpreters and use one that actually works well, but I know this takes time so I'm not throwing in things that huge. Maybe later, but UI first.
I have a some ideas, maybe some new,  which also might be more interessting, because you guys are better at programming But I need to put a bit more thought into them, so we can actually talk about the way Easy RPG (Player and Editor) could go. 

To make this short:
I'm not a friend of throwing in some half-baked application and releasing it to the user who will have to live with it. I'm aware this is where worlds collide, because I have a different approach on such things and open-source doensn't really work that way.

For me this is an opportunity to gain more experience about the whole UI on Android topic.
So this is how it will go down:
- I will continue my idea of an user-friendlier UI, where also your code comes into play. I'm not ignoring it, because it also saves me time.
- When the time is right I will introduce it in a new issue, so we can decide what's useful or not

In the end everyone wins: Easy RPG - hopefully - gets the UI it deserves, I gain experience and can figure out what could be done better usability-wise (e.g.: button layout editor).

**Comment by BlisterB** [comment]
Wtf did I just read?
For the black theme, just few posts above : 
> Minor stuff that drove me crazy while testing on older APIs, for example: white backgrounds and wrong text color. ;)

And what is this talk about supporting more RPG Maker version? That make no sense.
Same for the way you seem to describe your vision to contribute on an open source project. That just can't work that way : we won't be able to just cut/past the functionality we like.

Listen, I wanted to post a message to explain what is wrong with your post but in fact everything is pointing on the fact that you're making a sort of joke : your github account is totally empty, you didn't forked the project, you keep saying that the current port is not user friendly but you didn't propose anything except a video of a non functional mockup when I start to do PR, you keep saying that you will improve the current project but you avoid every attempt to distribute the work.

Eerf, I'm really sorry if you're not trolling. If it's the case please there some articles on the web explaining how to contribute on an open source/free software project. Just read them, because I can no longer paying attention to your post anymore if you continue this way, I'm just wasting time to read/answer them, calculate the fact that you're maybe doing a thing that I intend to do etc. etc.

**Comment by ItsSchoko** [comment]
White backgrounds on **MY** UI, because this whole post was about me failing on some lower API level stuff! Just put words in my mouth, thank you for that.

Yeah, this account is new. I created it so I could throw in this idea about UI stuff, because I was talking with one of the members about Easy RPG a couple months ago and we ended up talking about plans for a new UI which ended up being #925. 
Damn, I even spend some time on creating a mockup and you are accusing me of trolling. You just making it hard not to take this one personal, "sorry" won't help you.

A video of a non-functional mockup... yeah, it's not starting games, but the UI is real, a mockup usually doensn't have to do s*it anyways, because it's there to get the feeling how something could be approached, a UI test, not a player test.

When it comes to contribution: I said I would throw in my idea and we all can talk, not that I would insist that my idea is the best and has to be taken.
This whole thing is a mix of me gaining experience on a certain topic and doing useful stuff to contribute in the future.
