### ISSUE TITLE
Android: The red setting icon obscures the game setting icon of the game in the bottom right corner

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#996]
That's a funny corner case reported by a comment on google play:

When you have exactly the amount of games that fits on screen (= no scrolling) then the red settings button floats over the last game and hides the settings button of the game :D

Maybe you could add a longpress @BlisterB, or some other idea to prevent this?

**Comment by BlisterB** [comment]
Yes that was why I wanted to put this button settings in the action bar x).
This is actually the best fix to adopt. I put that on the next commit.

**Comment by Ghabry** [comment]
But... in the action bar nobody will find the button again and then nobody can add SHIFT. :o

**Comment by BlisterB** [comment]
Ow okay, actually I misunderstood your idea :p. Just so you know Google doesn't want long press for displaying menu anymore : 
"One final gesture to consider is long-press. On Android, long-pressing an item should either select it, begin dragging the item, or do nothing. Avoid using long-press for contextual menus, or less expected behaviors like shortcuts to other functionalities. Because long-press is a somewhat hidden gesture, its behavior isn’t normally apparent, so it’s especially best to stick to platform norms. If you really need to expose contextual actions on items, use an onscreen affordance like the overflow icon and popup menu."
https://design.google.com/articles/design-from-ios-to-android/

My idea was to put the setting's icon next to the "refresh" icon to keep a good visibility s (+ there is a like in the left menu). To be "google compliant".
"Side navigation : If side navigation such as a navigation drawer exists, include “Settings” below all other items (except Help & Feedback).
Apps without navigation : Place Settings in the toolbar menu below all other items (except Help & Feedback)"
https://material.google.com/patterns/settings.html#settings-placement

To be clear I'm not against your idea at all (I don't really care), I'll just give you information and I'll do what you want x).

**Comment by Ghabry** [comment]
right the settings are also in the left swipe out menu... yeah so remove this red button and place it to the top... at least if Samsung allows this :P
